"use strict";

const MAILBOX = "publishing@jmerrill.one";
const GRAPH_BASE = "https://graph.microsoft.com/v1.0";
const GRAPH_SCOPE = "https://graph.microsoft.com/.default";

const DETECTION_SOURCE = {
  GRAPH_NOTIFICATION: "GRAPH_NOTIFICATION",
  DELTA_RECONCILIATION: "DELTA_RECONCILIATION",
  SHADOW_READ: "SHADOW_READ",
  SYNTHETIC: "SYNTHETIC"
};

const PROCESSING_STATUS = {
  DETECTED: "DETECTED",
  INGESTED: "INGESTED",
  CLASSIFIED: "CLASSIFIED",
  CORRELATED: "CORRELATED",
  ROUTED: "ROUTED",
  PROCESSED: "PROCESSED",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  FAILED: "FAILED"
};

const CLASSIFICATION_AUTHORITY = {
  DETERMINISTIC: "DETERMINISTIC",
  HIGH_CONFIDENCE: "HIGH_CONFIDENCE",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  UNCLASSIFIED: "UNCLASSIFIED"
};

const MESSAGE_CLASS = {
  AUTHOR_RESPONSE: "AUTHOR_RESPONSE",
  AUTHOR_QUESTION: "AUTHOR_QUESTION",
  AUTHOR_APPROVAL: "AUTHOR_APPROVAL",
  AUTHOR_REQUEST_CHANGES: "AUTHOR_REQUEST_CHANGES",
  AUTHOR_CLARIFICATION: "AUTHOR_CLARIFICATION",
  AUTHOR_HOLD_REQUEST: "AUTHOR_HOLD_REQUEST",
  AUTHOR_DECLINE: "AUTHOR_DECLINE",
  MANUSCRIPT_SUBMISSION: "MANUSCRIPT_SUBMISSION",
  MANUSCRIPT_REVISION: "MANUSCRIPT_REVISION",
  COMMERCIAL_CONFIRMATION: "COMMERCIAL_CONFIRMATION",
  AGREEMENT_RESPONSE: "AGREEMENT_RESPONSE",
  PAYMENT_CORRESPONDENCE: "PAYMENT_CORRESPONDENCE",
  ROYALTY_REPORT: "ROYALTY_REPORT",
  SALES_REPORT: "SALES_REPORT",
  DISTRIBUTION_REPORT: "DISTRIBUTION_REPORT",
  DISTRIBUTOR_NOTICE: "DISTRIBUTOR_NOTICE",
  METADATA_NOTICE: "METADATA_NOTICE",
  METADATA_EXCEPTION: "METADATA_EXCEPTION",
  PRODUCTION_NOTICE: "PRODUCTION_NOTICE",
  PRODUCTION_EXCEPTION: "PRODUCTION_EXCEPTION",
  RIGHTS_INQUIRY: "RIGHTS_INQUIRY",
  PERMISSIONS_CORRESPONDENCE: "PERMISSIONS_CORRESPONDENCE",
  LEGAL_CORRESPONDENCE: "LEGAL_CORRESPONDENCE",
  INVOICE: "INVOICE",
  FEE_NOTICE: "FEE_NOTICE",
  PLATFORM_NOTICE: "PLATFORM_NOTICE",
  SECURITY_NOTICE: "SECURITY_NOTICE",
  MARKETING_INQUIRY: "MARKETING_INQUIRY",
  GENERAL_AUTHOR_CORRESPONDENCE: "GENERAL_AUTHOR_CORRESPONDENCE",
  SPAM_SOLICITATION: "SPAM_SOLICITATION",
  UNCLASSIFIED: "UNCLASSIFIED"
};

const QUEUE_CATEGORY = {
  AUTHOR_RESPONSE_ACTION_REQUIRED: "Author Response - Action Required",
  AUTHOR_QUESTION: "Author Question",
  AUTHOR_CLARIFICATION: "Author Clarification",
  MANUSCRIPT_SUBMISSION: "Manuscript Submission",
  MANUSCRIPT_REVISION: "Manuscript Revision",
  COMMERCIAL_RESPONSE: "Commercial Response",
  AGREEMENT_RESPONSE: "Agreement Response",
  ROYALTY_REPORT_RECEIVED: "Royalty Report Received",
  DISTRIBUTOR_NOTICE: "Distributor Notice",
  METADATA_EXCEPTION: "Metadata Exception",
  PRODUCTION_EXCEPTION: "Production Exception",
  RIGHTS_INQUIRY: "Rights Inquiry",
  INVOICE_FEE_NOTICE: "Invoice / Fee Notice",
  UNCLASSIFIED_PUBLISHING_MAIL: "Unclassified Publishing Mail"
};

const SUPPORTED_ATTACHMENT_EXTENSIONS = new Set([
  "docx",
  "pdf",
  "xlsx",
  "csv",
  "zip",
  "jpg",
  "jpeg",
  "png",
  "epub"
]);

module.exports = {
  MAILBOX,
  GRAPH_BASE,
  GRAPH_SCOPE,
  DETECTION_SOURCE,
  PROCESSING_STATUS,
  CLASSIFICATION_AUTHORITY,
  MESSAGE_CLASS,
  QUEUE_CATEGORY,
  SUPPORTED_ATTACHMENT_EXTENSIONS
};
