// Engine: Canon Guard
// Reusable? Y
// Stage-specific exception? N

export type CanonGuardId =
  | 'A1'
  | 'A2'
  | 'A3'
  | 'A4'
  | 'A5'
  | 'B1'
  | 'B2'
  | 'B3'
  | 'B4'
  | 'B5'
  | 'B6'
  | 'B7'
  | 'B8'
  | 'C1'
  | 'C2'
  | 'C3'
  | 'D1'
  | 'D2'
  | 'D3'
  | 'D4'

export class CanonGuardViolation extends Error {
  readonly guardId: CanonGuardId
  readonly failureCode: string
  readonly executionLogEventId: string

  constructor(guardId: CanonGuardId, failureCode: string, detail: string) {
    super(`CANON_GUARD_BLOCKED:${guardId}:${failureCode}:${detail}`)
    this.name = 'CanonGuardViolation'
    this.guardId = guardId
    this.failureCode = failureCode
    this.executionLogEventId = canonGuardFailureEventId(guardId)
  }
}

export function canonGuardFailureEventId(guardId: CanonGuardId) {
  return `CANON_GUARD_FAILURE_${guardId}`
}

export function canonGuardFailureLog(input: { guardId: CanonGuardId; failureCode: string; detail: string; sourceRecordId?: string }) {
  return {
    eventId: canonGuardFailureEventId(input.guardId),
    actionType: canonGuardFailureEventId(input.guardId),
    name: `${canonGuardFailureEventId(input.guardId)} - ${input.failureCode}`,
    description: `Canon guard ${input.guardId} blocked execution: ${input.failureCode}. ${input.detail}`,
    sourceEntity: 'jm1_canon_guard',
    sourceRecordId: input.sourceRecordId || input.guardId,
  }
}

function fail(guardId: CanonGuardId, failureCode: string, detail: string): never {
  throw new CanonGuardViolation(guardId, failureCode, detail)
}

export function enforceA1Renderer(input: { metadata?: { standard?: string; renderer?: string; qualityGate?: string } }) {
  if (input.metadata?.standard !== 'JM1 Enterprise Communication Standard v1.0') {
    fail('A1', 'ECR_STANDARD_MISSING', 'Message metadata does not prove governed ECR rendering.')
  }
  if (input.metadata?.renderer !== 'JM1 Enterprise Communication Renderer') {
    fail('A1', 'ECR_RENDERER_MISSING', 'Message metadata does not identify the governed renderer.')
  }
  if (input.metadata?.qualityGate !== 'PASS') fail('A1', 'ECR_QUALITY_GATE_NOT_PASS', 'Renderer quality gate did not pass.')
}

export function enforceA2SenderReplyTo(input: { brand: 'publishing'; from: string; replyTo: string }) {
  if (input.brand === 'publishing' && input.from.trim().toLowerCase() !== 'publishing@email.jmerrill.one') {
    fail('A2', 'SENDER_NOT_CANONICAL', 'Publishing author communications must use ACS sender publishing@email.jmerrill.one.')
  }
  if (input.brand === 'publishing' && input.replyTo.trim().toLowerCase() !== 'publishing@jmerrill.one') {
    fail('A2', 'REPLY_TO_NOT_CANONICAL', 'Publishing author communications must reply to publishing@jmerrill.one.')
  }
}

export function enforceA3NoInternalHeadingLeakage(input: { html?: string; text?: string; brandName: string }) {
  const html = input.html || ''
  const text = input.text || ''
  const brand = escapeRegExp(input.brandName)
  if (new RegExp(`<h1[^>]*>\\s*${brand}\\s*</h1>`, 'i').test(html)) {
    fail('A3', 'BARE_BRAND_H1', 'Brand name rendered as message H1 instead of governed brand header.')
  }
  if (new RegExp(`(^|\\n)\\s*#?\\s*${brand}\\s*(\\n|$)`, 'i').test(text) && !/The Publishing Team/i.test(text)) {
    fail('A3', 'BARE_BRAND_TEXT_HEADER', 'Plain text includes an ungoverned bare brand header.')
  }
}

export function enforceA4AuthorPackageAttachmentSet(input: { attachments: Array<{ fileName: string; contentType: string }> }) {
  const extensions = input.attachments.map((attachment) => extensionOf(attachment.fileName)).sort()
  if (extensions.length !== 2 || extensions[0] !== 'docx' || extensions[1] !== 'pdf') {
    fail('A4', 'AUTHOR_PACKAGE_ATTACHMENT_SET_INVALID', `Expected exactly DOCX + PDF; received ${extensions.join(',') || 'none'}.`)
  }
  const invalid = input.attachments.find(
    (attachment) => /\.(txt|md|markdown|json)$/i.test(attachment.fileName) || /text\/|markdown|json/i.test(attachment.contentType),
  )
  if (invalid) fail('A4', 'AUTHOR_PACKAGE_INTERNAL_ATTACHMENT_TYPE', `${invalid.fileName} is not an approved package attachment type.`)
}

export function enforceA5NoInternalArtifacts(input: { values: string[] }) {
  const joined = input.values.join('\n')
  const pattern =
    /\b(Generated by JM1 Automation|stage names?|checksums?|correlation ids?|correlationId|artifact ids?|artifactId|execution state|workflow record|Dataverse|manifest|ledger|internal instruction)\b/i
  if (pattern.test(joined)) fail('A5', 'INTERNAL_ARTIFACT_PATTERN_EXPOSED', 'Author-facing content contains internal metadata.')
}

export function enforceB1TrimSize(input: { widthIn: number; heightIn: number; standardTrim?: boolean }) {
  if (input.standardTrim === false) return
  if (Math.abs(input.widthIn - 6) > 0.01 || Math.abs(input.heightIn - 9) > 0.01) {
    fail('B1', 'TRIM_SIZE_NOT_6X9', `Expected 6x9; received ${input.widthIn}x${input.heightIn}.`)
  }
}

export function enforceB2FrontMatterSequence(input: { elements: string[] }) {
  const required = ['title', 'copyright', 'disclaimer', 'toc']
  const order = ['half-title', 'title', 'copyright', 'disclaimer', 'dedication', 'epigraph', 'toc', 'foreword', 'preface', 'introduction']
  for (const item of required) {
    if (!input.elements.includes(item)) fail('B2', 'FRONT_MATTER_REQUIRED_ELEMENT_MISSING', `${item} is required.`)
  }
  const positions = input.elements.map((item) => order.indexOf(item)).filter((index) => index >= 0)
  if (positions.some((position, index) => index > 0 && position < positions[index - 1])) {
    fail('B2', 'FRONT_MATTER_OUT_OF_ORDER', 'Front matter order does not match JMP Print Interior Standard v1.0.')
  }
}

export function enforceB3Pagination(input: {
  frontMatterFoliosVisible: boolean
  firstChapterPageNumber: number
  firstChapterRecto: boolean
  chapterOpeningHeaderVisible: boolean
  chapterOpeningFooterVisible: boolean
  chapterOpeningFolioVisible: boolean
  continuationPageRunningHeaderPresent: boolean
  continuationPageFolioPresent: boolean
  laterChapterStarts?: Array<{ chapterLabel: string; pageSide: 'recto' | 'verso'; artificialBlankPageBefore: boolean }>
}) {
  if (input.frontMatterFoliosVisible) fail('B3', 'FRONT_MATTER_FOLIOS_VISIBLE', 'Front matter folios must be suppressed.')
  if (input.firstChapterPageNumber !== 1) fail('B3', 'CHAPTER_ONE_NOT_ARABIC_ONE', 'Chapter 1 must begin Arabic page 1.')
  if (!input.firstChapterRecto) fail('B3', 'CHAPTER_ONE_NOT_RECTO', 'Chapter 1 must begin on a right-hand page.')
  if (input.chapterOpeningHeaderVisible) fail('B3', 'CHAPTER_OPENING_HEADER_VISIBLE', 'Chapter openings must suppress running headers.')
  if (input.chapterOpeningFooterVisible) fail('B3', 'CHAPTER_OPENING_FOOTER_VISIBLE', 'Chapter openings must suppress footers.')
  if (input.chapterOpeningFolioVisible) fail('B3', 'CHAPTER_OPENING_FOLIO_VISIBLE', 'Chapter openings must suppress folios.')
  if (!input.continuationPageRunningHeaderPresent) {
    fail('B3', 'CONTINUATION_RUNNING_HEADER_MISSING', 'Eligible continuation pages must carry running headers.')
  }
  if (!input.continuationPageFolioPresent) fail('B3', 'CONTINUATION_FOLIO_MISSING', 'Eligible continuation pages must carry folios.')
  const forcedLaterChapter = (input.laterChapterStarts || []).find((chapter) => chapter.artificialBlankPageBefore)
  if (forcedLaterChapter) {
    fail('B3', 'LATER_CHAPTER_FORCED_RECTO', `${forcedLaterChapter.chapterLabel} has an artificial blank page solely for recto opening.`)
  }
}

export function enforceB4SingleDisclaimer(input: { disclaimerCount: number; containsLibraryLabels?: boolean }) {
  if (input.disclaimerCount !== 1) fail('B4', 'DISCLAIMER_COUNT_INVALID', `Expected one disclaimer; received ${input.disclaimerCount}.`)
  if (input.containsLibraryLabels) fail('B4', 'DISCLAIMER_LIBRARY_EXPOSED', 'Disclaimer library/category labels must not render.')
}

export function enforceB5ConditionalLegalFields(input: { renderedText: string }) {
  if (/\b(LCCN|Copyright Registration|Cover Credit|Editor Credit|ISBN)\s*:\s*(\n|$)/i.test(input.renderedText)) {
    fail('B5', 'BLANK_LEGAL_PLACEHOLDER_RENDERED', 'Unverified legal field rendered as a blank placeholder.')
  }
  if (/\{\{[^}]+}}|<<[^>]+>>|\bTBD\b|\bPLACEHOLDER\b/i.test(input.renderedText)) {
    fail('B5', 'LEGAL_PLACEHOLDER_TOKEN_RENDERED', 'Template placeholder rendered in production output.')
  }
}

export function enforceB6IsbnByFormat(input: { contractedFormats: string[]; renderedIsbns: Array<{ format: string; isbn?: string }> }) {
  const contracted = new Set(input.contractedFormats.map((format) => format.toLowerCase()))
  for (const row of input.renderedIsbns) {
    if (!contracted.has(row.format.toLowerCase())) fail('B6', 'ISBN_FORMAT_NOT_CONTRACTED', `${row.format} is not a contracted format.`)
    if (!row.isbn?.trim()) fail('B6', 'BLANK_ISBN_RENDERED', `${row.format} has a blank ISBN label.`)
  }
}

export function enforceB7NoSampleContent(input: { renderedText: string }) {
  if (/\b(SAMPLE_ONLY|Vellum Reviews|Book\s+[1-6]\b|placeholder chapter|demo content)\b/i.test(input.renderedText)) {
    fail('B7', 'SAMPLE_CONTENT_RENDERED', 'Sample or library-only content appeared in production output.')
  }
}

export function enforceB8TocExclusions(input: { tocEntries: string[]; approvedHeadings: string[]; excludedPatterns?: RegExp[] }) {
  const approved = new Set(input.approvedHeadings.map(normalizeHeading))
  const excluded = input.excludedPatterns || [/Soul Dive/i, /internal/i, /reference material/i]
  for (const entry of input.tocEntries) {
    if (excluded.some((pattern) => pattern.test(entry))) fail('B8', 'TOC_EXCLUDED_ENTRY_RENDERED', `${entry} is not approved for TOC.`)
    if (!approved.has(normalizeHeading(entry))) fail('B8', 'TOC_ENTRY_NOT_IN_APPROVED_HEADINGS', `${entry} is not in approved heading inventory.`)
  }
}

export function enforceC1LoginAvailability(input: { loginRendered: boolean; knownGoodAuthPasses: boolean }) {
  if (!input.loginRendered) fail('C1', 'LOGIN_SCREEN_NOT_RENDERED', 'Author/Publisher Operating Center login must render.')
  if (!input.knownGoodAuthPasses) fail('C1', 'KNOWN_GOOD_AUTH_FAILED', 'Known-good active account could not authenticate.')
}

export function enforceC2IdentityResolution(input: { matches: Array<{ contactId: string }>; activeAuthor: boolean }) {
  if (!input.activeAuthor) return
  if (input.matches.length !== 1) fail('C2', 'AUTHOR_IDENTITY_NOT_SINGLE_CANONICAL_CONTACT', `Resolved ${input.matches.length} contacts.`)
}

export function enforceC3PackageReviewAction(input: { ctas: Array<{ label: string; href?: string; handlerBound?: boolean }> }) {
  const reviewCta = input.ctas.find((cta) => /review package|reply|approve/i.test(cta.label))
  if (!reviewCta) fail('C3', 'REVIEW_PACKAGE_CTA_MISSING', 'Author review CTA is required.')
  if (!reviewCta.href && !reviewCta.handlerBound) fail('C3', 'REVIEW_PACKAGE_CTA_DEAD', 'Author review CTA has no bound handler or URL.')
}

export function enforceD1DuplicateTitlePrevention(input: { activeMatches: Array<{ titleId: string }>; authorWorkKey: string }) {
  if (input.activeMatches.length > 0) {
    fail('D1', 'ACTIVE_TITLE_DUPLICATE_DETECTED', `Existing active title found for ${input.authorWorkKey}.`)
  }
}

export function enforceD2AutoAdvanceOnApproval(input: { approvedAt?: string; advancedAt?: string; now: string; thresholdHours?: number }) {
  if (!input.approvedAt || input.advancedAt) return
  const thresholdMs = (input.thresholdHours ?? 24) * 60 * 60 * 1000
  if (Date.parse(input.now) - Date.parse(input.approvedAt) > thresholdMs) {
    fail('D2', 'APPROVED_STAGE_ADVANCE_STALLED', `Approved stage has not advanced within ${input.thresholdHours ?? 24} hours.`)
  }
}

export function enforceD3SampleDataExclusion(input: { assets: Array<{ name: string; tags?: string[]; authorFacingAdjacent?: boolean }> }) {
  const sample = input.assets.find((asset) => asset.authorFacingAdjacent && (asset.tags || []).some((tag) => /SAMPLE_ONLY|test/i.test(tag)))
  if (sample) fail('D3', 'SAMPLE_DATA_IN_AUTHOR_ADJACENT_SPACE', `${sample.name} is tagged as sample/test in an author-adjacent space.`)
}

export function enforceD4SchedulingTargetAuthority(input: { availabilityIdentity: string; writeIdentity: string }) {
  if (input.availabilityIdentity.trim().toLowerCase() !== input.writeIdentity.trim().toLowerCase()) {
    fail('D4', 'SCHEDULING_AVAILABILITY_WRITE_IDENTITY_SPLIT', 'Bookings availability source must match calendar write target.')
  }
}

function extensionOf(fileName: string) {
  return fileName.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1] || ''
}

function normalizeHeading(value: string) {
  return value.trim().replace(/\s+/g, ' ').toLowerCase()
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
