"use strict";

require("./functions/getPublisherRecommendationReview");
require("./functions/runAgreementDocumentPreparation");
require("./functions/runAgreementPackageSend");
require("./functions/runGovernedAgreementGeneration");
require("./functions/runApprovalEventConsumer");
require("./functions/runAuthorReviewResponseConsumer");
require("./functions/runEditorialExecutionRuntime");
require("./functions/runEditorialPackageHandoffConsumer");
require("./functions/runEditorialNextStageMaterialization");
require("./functions/runTargetedEditorialExecution");
require("./functions/runEditorialReviewNow");
require("./functions/runIntentionalLeaderAuthorResponse");
require("./functions/runMilestone6ContinuationCommunication");
require("./functions/runMilestone6EvidenceRecoveryLog");
require("./functions/runMilestone6OpportunityUpdate");
require("./functions/runMilestone6PaymentOptionCapture");
require("./functions/runOp000TrackAAdoption");
require("./functions/runOp000TrackBAdoption");
require("./functions/runPackageSelectionCommercialContinuation");
require("./functions/runPreContractEditorialReview");
require("./functions/runPublisherRecommendationAction");
require("./functions/runPublisherReviewDecision");
require("./functions/runPublishingIntakeAutostartRecovery");
require("./functions/runPublishingMailboxReplyCheck");
require("./functions/runStage0Diagnostic");
require("./functions/signNowWebhook");
