"use strict";

const assert = require("node:assert/strict");
const test = require("node:test");
const { Document, Packer, Paragraph } = require("docx");
const {
  certifyAuthorManuscriptAttachment,
  certifyEmailLastMile
} = require("../src/policy/humanLastMileCertification");

async function docxBuffer(paragraphs) {
  const doc = new Document({
    sections: [{ children: paragraphs.map((text) => new Paragraph(text)) }]
  });
  return Packer.toBuffer(doc);
}

test("email last-mile certification rejects Establishing Glory bad greeting", () => {
  const result = certifyEmailLastMile({
    authorName: "Jackie Smith Jr",
    body: "Good day Jackie Smith Jr,\n\nPlease reply with Approved.\n\nThe Publishing Team\nJ Merrill Publishing, Inc.",
    htmlBody: "<!doctype html><html><body><p>Good day Jackie Smith Jr,</p><p>Please reply with Approved.</p><p>The Publishing Team<br>J Merrill Publishing, Inc.</p></body></html>"
  });

  assert.equal(result.decision, "DENY");
  assert.ok(result.violations.includes("GREETING_FULL_NAME_WITHOUT_COMMA"));
});

test("email last-mile certification rejects internal author-review language and heading bloat", () => {
  const result = certifyEmailLastMile({
    authorName: "Jackie Smith Jr",
    body: "Good day, Jackie,\n\nThe current author-facing files are ready for the current publishing stage. Reply with Approved. The next step follows.\n\nThe Publishing Team\nJ Merrill Publishing, Inc.",
    htmlBody: "<!doctype html><html><body><p>Good day, Jackie,</p><h1>A</h1><h2>B</h2><h2>C</h2><p>The current author-facing files are ready for the current publishing stage.</p><p>The Publishing Team<br>J Merrill Publishing, Inc.</p></body></html>"
  });

  assert.equal(result.decision, "DENY");
  assert.ok(result.violations.some((item) => item.startsWith("INTERNAL_LANGUAGE:")));
  assert.ok(result.violations.includes("ROUTINE_EMAIL_TEMPLATE_BLOAT:3_HEADINGS"));
});

test("author manuscript last-mile certification rejects internal automation wrapper docx", async () => {
  const buffer = await docxBuffer([
    "Generated by: JM1 Automation",
    "Governed Developmental Revision Artifact",
    "Source artifact: cb07ca7d-b784-f111-ab0f-6045bdd69678",
    "Source checksum: e09414df4b3c42854bba496caca14264a68186467d746be39963d5d5885b9a6b",
    "Correlation ID: TEST",
    "Publisher review note before author-facing release"
  ]);
  const result = await certifyAuthorManuscriptAttachment({
    role: "editedManuscript",
    fileName: "Establishing Glory - Edited Manuscript.docx",
    buffer
  });

  assert.equal(result.decision, "DENY");
  assert.ok(result.violations.some((item) => item.startsWith("INTERNAL_METADATA_LEAK:")));
});

test("author manuscript last-mile certification allows plausible clean manuscript docx", async () => {
  const paragraphs = [
    "Establishing Glory: The Library",
    "Chapter One",
    ...Array.from({ length: 900 }, (_, index) => `This clean manuscript paragraph ${index + 1} contains story text for review and continues the book with character, scene, voice, continuity, and chapter movement.`),
    "The End"
  ];
  const buffer = await docxBuffer(paragraphs);
  const result = await certifyAuthorManuscriptAttachment({
    role: "editedManuscript",
    fileName: "Establishing Glory - Edited Manuscript.docx",
    buffer
  });

  assert.equal(result.decision, "ALLOW");
  assert.equal(result.wordCount > 5000, true);
});
