"use strict";

const { describe, test } = require("node:test");
const assert = require("node:assert/strict");
const {
  ACCEPTANCE_OUTCOME,
  PRICING_STATES,
  classifyPackageAcceptance,
  buildPackageAcceptedEvent,
  buildOfferPreview,
  renderPaymentOptionsResponsePreview,
  lockPricingSnapshotFromPreview,
  buildOpportunityStatusProjection,
  buildExistingAuthorPreview
} = require("../src/author/packageAcceptancePaymentOptions");
const {
  TEMPLATE_NAME,
  renderPackageAcceptanceCommunication,
  validatePackageAcceptanceCommunication
} = require("../src/author/packageAcceptanceCommunicationBuilder");
const { PACKAGE_CODES, NEW_FINANCING_POLICY_VERSION } = require("../src/author/authorOfferEngine");
const { computeInstallmentStripeAmountFromAuthorOffer } = require("../src/payment/agreementPaymentLinkMapping");

function packageEvent(overrides = {}) {
  return buildPackageAcceptedEvent({
    diagnosticId: "48cd0d86-f595-f111-8076-6045bdd69435",
    authorId: "author-1",
    titleId: "title-1",
    title: "Test Title",
    intakeReferenceCode: "JMP-INT-202608-ABC123",
    selectedPackageCode: PACKAGE_CODES.STARTER,
    decisionTimestamp: "2026-08-20T12:00:00Z",
    supportingCommunicationId: "message-1",
    ...overrides
  });
}

function plan(preview, code) {
  return preview.offer.paymentOptions.find((item) => item.planCode === code);
}

describe("package acceptance semantics", () => {
  test("explicit package acceptance resolves", () => {
    const result = classifyPackageAcceptance({ replyText: "Yes, I'd like to move forward with Professional." });
    assert.equal(result.outcome, ACCEPTANCE_OUTCOME.ACCEPTED);
    assert.equal(result.selectedPackageCode, PACKAGE_CODES.PROFESSIONAL);
  });

  test("sole Starter recommendation plus yes resolves to Starter", () => {
    const result = classifyPackageAcceptance({
      replyText: "Yes, I want to proceed with the recommended package.",
      primaryPackageCode: PACKAGE_CODES.STARTER,
      presentedPackageCodes: [PACKAGE_CODES.STARTER]
    });
    assert.equal(result.outcome, ACCEPTANCE_OUTCOME.ACCEPTED);
    assert.equal(result.selectedPackageCode, PACKAGE_CODES.STARTER);
    assert.equal(result.reason, "SOLE_STARTER_RECOMMENDATION_ACCEPTED");
  });

  test("two selectable packages plus ambiguous yes requires clarification", () => {
    const result = classifyPackageAcceptance({
      replyText: "Yes",
      presentedPackageCodes: [PACKAGE_CODES.PROFESSIONAL, PACKAGE_CODES.STARTER]
    });
    assert.equal(result.outcome, ACCEPTANCE_OUTCOME.CLARIFICATION_REQUIRED);
    assert.equal(result.selectedPackageCode, null);
  });

  test("vague interest is not package acceptance", () => {
    const result = classifyPackageAcceptance({
      replyText: "Sounds good. I'm interested.",
      presentedPackageCodes: [PACKAGE_CODES.PROFESSIONAL]
    });
    assert.equal(result.outcome, ACCEPTANCE_OUTCOME.NO_ACCEPTANCE);
  });

  test("duplicate response produces no second acceptance event", () => {
    const result = classifyPackageAcceptance({
      replyText: "I choose the Starter package.",
      existingAcceptanceEvents: [{ id: "existing" }]
    });
    assert.equal(result.outcome, ACCEPTANCE_OUTCOME.DUPLICATE);
  });
});

describe("automatic payment response preview", () => {
  test("new Starter author immediately receives Full / 2 / 4 / 8 preview options", () => {
    const preview = buildOfferPreview({ packageAcceptedEvent: packageEvent() });
    assert.equal(preview.ok, true);
    assert.equal(preview.pricingState, PRICING_STATES.PAYMENT_OPTION_SELECTION_PENDING);
    assert.deepEqual(preview.offer.paymentOptions.map((item) => item.planCode), ["FULL_PAY", "2_PAY", "4_PAY", "8_PAY"]);
  });

  test("new Professional author receives options generated by the Offer Engine", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PROFESSIONAL })
    });
    assert.equal(preview.offer.adjustedPackagePrincipalFormatted, "$4,500.00");
    assert.equal(plan(preview, "8_PAY").totalDueFormatted, "$4,680.00");
  });

  test("Quanishia implementation case receives new financing policy preview, not legacy 4 percent", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({
        selectedPackageCode: PACKAGE_CODES.PROFESSIONAL,
        authorId: "5bb796dc-cd95-f111-8076-7c1e525b15c2",
        authorName: "Quanishia Dockery",
        title: "Indomitable",
        intakeReferenceCode: "JMP-INT-202608-0AOS7L"
      }),
      paymentPolicyVersion: NEW_FINANCING_POLICY_VERSION
    });
    assert.equal(preview.offer.paymentPolicyVersion, NEW_FINANCING_POLICY_VERSION);
    assert.equal(plan(preview, "2_PAY").totalDueFormatted, "$4,522.50");
    assert.equal(plan(preview, "4_PAY").totalDueFormatted, "$4,567.50");
    assert.equal(plan(preview, "8_PAY").totalDueFormatted, "$4,657.50");
    assert.equal(plan(preview, "8_PAY").multiPayFeeTotalFormatted, "$0.00");
    assert.equal(plan(preview, "8_PAY").planChargeTotalFormatted, "$157.50");
  });

  test("returning Professional author has loyalty automatically applied", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PROFESSIONAL }),
      priorEligibleTitleCount: 2
    });
    assert.equal(preview.offer.returningAuthorPercent, 15);
    assert.equal(preview.offer.adjustedPackagePrincipalFormatted, "$3,825.00");
  });

  test("referral credits present show referral selection first", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PREMIER }),
      priorEligibleTitleCount: 4,
      referralCreditsAvailablePercent: 40
    });
    assert.equal(preview.pricingState, PRICING_STATES.REFERRAL_SELECTION_PENDING);
    assert.equal(preview.referralSelectionRequired, true);
    assert.deepEqual(preview.offer.referralCreditChoicesPercent, [0, 10, 20, 30]);
  });

  test("cap restricts selectable credits and selected credits recalculate exact options", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PREMIER }),
      priorEligibleTitleCount: 4,
      referralCreditsAvailablePercent: 40,
      referralCreditsSelectedPercent: 30
    });
    assert.equal(preview.offer.returningAuthorPercent, 20);
    assert.equal(preview.offer.referralCreditsAppliedPercent, 30);
    assert.equal(preview.offer.combinedBenefitPercent, 50);
    assert.equal(preview.offer.adjustedPackagePrincipalFormatted, "$3,750.00");
    assert.equal(plan(preview, "8_PAY").installments[0].totalDueFormatted, "$487.50");
  });

  test("renderer consumes canonical offer output and does not send", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PROFESSIONAL }),
      priorEligibleTitleCount: 2,
      referralCreditsAvailablePercent: 20,
      referralCreditsSelectedPercent: 20
    });
    const response = renderPaymentOptionsResponsePreview(preview);
    assert.equal(response.ok, true);
    assert.equal(response.rendererAuthority, "FORMAT_ONLY_CONSUMES_AUTHOR_OFFER_ENGINE_OUTPUT");
    assert.equal(response.liveAutoSendEnabled, false);
    assert.match(response.textBody, /\$2,925\.00/);
    assert.match(response.textBody, /\$3,042\.00 total/);
  });

  test("commissioning preview has no live author send", () => {
    const response = renderPaymentOptionsResponsePreview(buildOfferPreview({ packageAcceptedEvent: packageEvent() }));
    assert.equal(response.liveAutoSendEnabled, false);
    assert.equal(response.negativeProof.liveAutoSendBeforeCommissioning, 0);
  });

  test("package-acceptance communication renders canonical HTML/text from Author Offer Engine output", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({
        selectedPackageCode: PACKAGE_CODES.PROFESSIONAL,
        title: "New Book Test",
        intakeReferenceCode: "JMP-INT-202608-ABC123"
      }),
      priorEligibleTitleCount: 2,
      referralCreditsAvailablePercent: 20,
      referralCreditsSelectedPercent: 20
    });
    const communication = renderPackageAcceptanceCommunication(preview, {
      authorName: "Author",
      authorEmail: "author@example.com",
      title: "New Book Test",
      actionUrl: "https://jmerrill.pub/author/payment-options/test",
      approvedBy: "jackie",
      approvedOn: "2026-08-21T08:00:00.000Z"
    });

    assert.equal(communication.ok, true);
    assert.equal(communication.sendApproval.messageType, "APPROVED_AUTHOR_RESPONSE");
    assert.equal(communication.sendApproval.templateName, TEMPLATE_NAME);
    assert.equal(communication.sendApproval.subject, "Your Publishing Payment Options for New Book Test");
    assert.match(communication.sendApproval.htmlBody, /Choose Your Payment Option/);
    assert.equal(communication.rendered.subject, "Your Publishing Payment Options for New Book Test");
    assert.doesNotMatch(communication.rendered.subject, /JMP-INT/);
    assert.match(communication.rendered.html, /J MERRILL PUBLISHING/);
    assert.ok(communication.rendered.html.indexOf("Payment Options") < communication.rendered.html.indexOf("Choose Your Payment Option"));
    assert.match(communication.rendered.text, /JMP-INT-202608-ABC123/);
    assert.match(communication.rendered.text, /\$2,925\.00/);
    assert.match(communication.rendered.text, /\$3,042\.00 \+ applicable tax/);
    assert.equal(communication.sendApproval.templateMetadata.renderer, "JM1 Enterprise Communication Renderer");
    assert.equal(communication.negativeProof.rendererRecalculatesPricing, 0);
  });

  test("package-acceptance communication can render the new financing terminology and short subject", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({
        selectedPackageCode: PACKAGE_CODES.PROFESSIONAL,
        title: "Indomitable",
        intakeReferenceCode: "JMP-INT-202608-0AOS7L"
      }),
      paymentPolicyVersion: NEW_FINANCING_POLICY_VERSION
    });
    const communication = renderPackageAcceptanceCommunication(preview, {
      authorName: "Quanishia",
      authorEmail: "quanishadockery7777@gmail.com",
      title: "Indomitable",
      subjectOverride: "Your Publishing Payment Options for Indomitable",
      actionUrl: "https://jmerrill.pub/author/payment-options/indomitable",
      approvedBy: "jackie"
    });
    assert.equal(communication.ok, true);
    assert.equal(communication.rendered.subject, "Your Publishing Payment Options for Indomitable");
    assert.match(communication.rendered.text, /Payment-plan charge/);
    assert.match(communication.rendered.text, /There is no early-payoff penalty/);
    assert.doesNotMatch(communication.rendered.text, /4% transaction fee/);
    assert.ok(communication.rendered.text.indexOf("Payment Options") < communication.rendered.text.indexOf("Choose Your Payment Option"));
  });

  test("package-acceptance communication keeps referral selection pending and does not auto-consume credit", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({
        selectedPackageCode: PACKAGE_CODES.PREMIER,
        title: "Referral Book"
      }),
      priorEligibleTitleCount: 4,
      referralCreditsAvailablePercent: 40
    });
    const communication = renderPackageAcceptanceCommunication(preview, {
      authorName: "Author",
      authorEmail: "author@example.com",
      title: "Referral Book",
      actionUrl: "https://jmerrill.pub/author/payment-options/referral",
      approvedBy: "jackie"
    });

    assert.equal(preview.pricingState, PRICING_STATES.REFERRAL_SELECTION_PENDING);
    assert.equal(communication.ok, true);
    assert.match(communication.rendered.text, /Referral credit available: 40%/);
    assert.match(communication.rendered.text, /Selectable now: 0% \/ 10% \/ 20% \/ 30%/);
    assert.equal(communication.previewState.pricingLocked, false);
    assert.equal(communication.negativeProof.referralAutoConsumed, 0);
  });

  test("package-acceptance validator rejects reference-led subjects, invented tax, premature family language, and pricing lock", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ title: "New Book Test" })
    });
    const communication = renderPackageAcceptanceCommunication(preview, {
      authorName: "Author",
      authorEmail: "author@example.com",
      title: "New Book Test",
      actionUrl: "https://jmerrill.pub/author/payment-options/test",
      approvedBy: "jackie"
    });
    const invalid = {
      ...communication.rendered,
      subject: "JMP-INT-202608-ABC123 - Payment Options",
      text: `${communication.rendered.text}\nTax will be $20.\nWelcome to the family.`
    };
    const lockedPreview = { ...preview, pricingState: PRICING_STATES.PRICING_LOCKED };
    const validation = validatePackageAcceptanceCommunication(invalid, lockedPreview);

    assert.equal(validation.ok, false);
    assert.ok(validation.blockers.includes("SUBJECT_LEADS_WITH_INTERNAL_REFERENCE"));
    assert.ok(validation.blockers.includes("TAX_FABRICATED"));
    assert.ok(validation.blockers.includes("PREMATURE_JOINED_THE_FAMILY_LANGUAGE"));
    assert.ok(validation.blockers.includes("PRICING_LOCKED_BEFORE_PAYMENT_SELECTION"));
  });
});

describe("monetary authority and locked snapshots", () => {
  test("renderer amounts equal Author Offer Engine amounts on odd-cent principal", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent(),
      priorEligibleTitleCount: 1,
      referralCreditsAvailablePercent: 10,
      referralCreditsSelectedPercent: 10
    });
    const eightPay = plan(preview, "8_PAY");
    const response = renderPaymentOptionsResponsePreview(preview);
    assert.equal(eightPay.installments.reduce((sum, row) => sum + row.principalCents, 0), preview.offer.adjustedPackagePrincipalCents);
    assert.match(response.textBody, new RegExp(eightPay.totalDueFormatted.replace(/[$.]/g, "\\$&")));
  });

  test("offer preview may change before lock, but locked pricing does not", () => {
    const first = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PROFESSIONAL }),
      priorEligibleTitleCount: 2,
      referralCreditsAvailablePercent: 20,
      referralCreditsSelectedPercent: 20
    });
    const locked = lockPricingSnapshotFromPreview(first, { planCode: "8_PAY", lockedAt: "2026-08-20T13:00:00Z" });
    const later = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PROFESSIONAL }),
      priorEligibleTitleCount: 2,
      referralCreditsAvailablePercent: 40,
      referralCreditsSelectedPercent: 35
    });
    assert.equal(locked.ok, true);
    assert.equal(locked.snapshot.snapshotStatus, PRICING_STATES.PRICING_LOCKED);
    assert.equal(locked.snapshot.adjustedPackagePrincipalCents, 292500);
    assert.equal(later.offer.adjustedPackagePrincipalCents, 225000);
  });

  test("payment-plan choice matches locked schedule and duplicate lock is idempotent", () => {
    const preview = buildOfferPreview({ packageAcceptedEvent: packageEvent() });
    const locked = lockPricingSnapshotFromPreview(preview, { planCode: "4_PAY", lockedAt: "2026-08-20T13:00:00Z" });
    const replay = lockPricingSnapshotFromPreview(preview, { existingSnapshot: locked.snapshot, planCode: "8_PAY" });
    assert.equal(locked.snapshot.paymentPlan.planCode, "4_PAY");
    assert.equal(replay.idempotent, true);
    assert.equal(replay.snapshot.paymentPlan.planCode, "4_PAY");
  });

  test("Stripe adapter consumes author-offer schedule for adjusted amounts", () => {
    const result = computeInstallmentStripeAmountFromAuthorOffer({
      packageCode: PACKAGE_CODES.PROFESSIONAL,
      paymentOptionCode: "TWO_PAYMENTS",
      priorEligibleTitleCount: 2,
      referralCreditsAvailablePercent: 20,
      referralCreditsRequestedPercent: 20
    });
    assert.equal(result.ok, true);
    assert.equal(result.totalUsd, 3042);
    assert.equal(result.installmentSchedule[0].totalDueFormatted, "$1,521.00");
  });

  test("Opportunity reflects locked price state without recalculating loyalty", () => {
    const projection = buildOpportunityStatusProjection({ pricingState: PRICING_STATES.PRICING_LOCKED });
    assert.equal(projection.jm1_m6packageselectionstatus, "PACKAGE_SELECTED");
    assert.equal(projection.jm1_m6paymentoptionselectionstatus, "PAYMENT_OPTION_SELECTED");
    assert.equal(projection.jm1_pricingstate, "PRICING_LOCKED");
  });

  test("20 loyalty plus 40 available referral with 30 selected preserves 10", () => {
    const preview = buildOfferPreview({
      packageAcceptedEvent: packageEvent({ selectedPackageCode: PACKAGE_CODES.PREMIER }),
      priorEligibleTitleCount: 4,
      referralCreditsAvailablePercent: 40,
      referralCreditsSelectedPercent: 30
    });
    assert.equal(preview.offer.referralCreditsRemainingPercent, 10);
    assert.equal(preview.referralLifecycle.reserved, "NOT_RESERVED_IN_PREVIEW");
    assert.equal(preview.liveActions.mutatesReferralBalance, false);
  });
});

describe("existing author read-only preview", () => {
  test("derives relationship tier without retroactive contract changes", () => {
    const preview = buildExistingAuthorPreview({
      authorId: "author-existing",
      packageCode: PACKAGE_CODES.PREMIER,
      priorEligibleTitleCount: 4,
      referralCreditsAvailablePercent: 10
    });
    assert.equal(preview.derivedLoyaltyPercent, 20);
    assert.equal(preview.referralCreditsAvailablePercent, 10);
    assert.equal(preview.retroactiveContractChanges, 0);
  });
});
