"use strict";

const FORBIDDEN_PATTERNS = Object.freeze([
  {
    code: "OVERLAY_TERM",
    pattern: /\b(?:editorial|genre|prompt|capability|system|model)\s+overlay\b|\boverlay\s+(?:profile|id|configuration|rule)\b/i
  },
  {
    code: "DOCTRINE_TERM",
    pattern: /\b(?:editorial|system|workflow|prompt|capability)\s+doctrine\b|\bdoctrine\s+(?:profile|id|configuration|rule)\b/i
  },
  { code: "OVERLAY_ID", pattern: /\bFAITH_INSPIRATIONAL\b|\bURBAN_STREET_LIT_VOICE_PRESERVATION\b|\bCHILDRENS_BOOK_STANDARD\b/i },
  {
    code: "MODEL_REASONING",
    pattern:
      /\bmodel reasoning\b|\bchain of thought\b|\b(?:system|model|hidden|internal) prompt\b|\bprompt(?:ing)? (?:instructions?|content|body)\b/i
  },
  { code: "INTERNAL_RULE_CITATION", pattern: /\binternal rule\b|\brule citation\b|\bpolicy reference\b/i },
  { code: "AI_AUTOMATION_REFERENCE", pattern: /\b(?:generated by (?:JM1|JMI)|AI model|AI assistant|automation|orchestrator|agentic runtime)\b/i },
  { code: "INTERNAL_PLATFORM_REFERENCE", pattern: /\b(?:Dataverse|Azure Functions?|Azure Communication Services|ACS relay|SharePoint implementation)\b/i },
  { code: "EXECUTION_IDENTIFIER", pattern: /\b(?:execution|correlation|capability|artifact|workflow)\s*(?:id|identifier)\b/i },
  { code: "GUID", pattern: /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i },
  { code: "CHECKSUM", pattern: /\b(?:sha-?256|checksum)\b|\b[a-f0-9]{64}\b/i },
  { code: "INTERNAL_STAGE_LABEL", pattern: /\b(?:DEVELOPMENTAL_EDITING|LINE_EDITING|COPYEDITING|PROOFREADING|EDITORIAL_INTERNAL_QA)\b/ },
  { code: "INTERNAL_PUBLISHER_NOTE", pattern: /\bPublisher review note(?:\s+P\d+)?\b/i },
  { code: "RIGHTS_LEGAL_INTERNAL_NOTE", pattern: /\b(?:legal posture|before author-facing release|rights\/legal internal|RIGHTS_LEGAL_INTERNAL)\b/i },
  { code: "TECHNICAL_ARTIFACT_WRAPPER", pattern: /\b(?:source artifact|source checksum|governed developmental revision artifact|extracted word count|extracted paragraph count)\b/i }
]);

function scan(value, path = "root", issues = []) {
  if (typeof value === "string") {
    FORBIDDEN_PATTERNS.forEach(({ code, pattern }) => {
      if (pattern.test(value)) {
        issues.push({ code, path, excerpt: value.slice(0, 160) });
      }
    });
    return issues;
  }

  if (Array.isArray(value)) {
    value.forEach((entry, index) => scan(entry, `${path}[${index}]`, issues));
    return issues;
  }

  if (value && typeof value === "object") {
    Object.entries(value).forEach(([key, entry]) => scan(entry, `${path}.${key}`, issues));
  }

  return issues;
}

function validateAuthorFacingProjection(payload) {
  const issues = scan(payload);
  return {
    ok: issues.length === 0,
    issues
  };
}

module.exports = {
  FORBIDDEN_PATTERNS,
  validateAuthorFacingProjection
};
