export const PUBLISHING_AUTHOR_EXPERIENCE_SURVEY = {
  division: 'J Merrill Publishing',
  sourceIdentifier: 'JMP-CV-01A-AUTHOR-EXPERIENCE',
  version: 'CV-01A',
  publicPath: '/experience',
  publicUrl: 'https://jmerrill.pub/experience/',
  surveyName: 'J Merrill Publishing Author Experience',
  feedbackButtonLabel: 'Share Your Experience',
  privacyNotice:
    'Please do not include payment details, private manuscript content, SSNs, bank information, medical details, or other sensitive personal information.',
  questions: [
    {
      id: 'onboarding',
      label: 'Onboarding experience',
      prompt: 'How would you rate the onboarding experience?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'communication',
      label: 'Communication clarity',
      prompt: 'How clear and helpful was the communication?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'clarity',
      label: 'Clarity of next steps',
      prompt: 'How clear were the next steps throughout the process?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'editorial',
      label: 'Editorial experience',
      prompt: 'How would you rate the editorial experience?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'production',
      label: 'Production experience',
      prompt: 'How would you rate the production experience?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'heard',
      label: 'Feeling heard and respected',
      prompt: 'How well did you feel heard and respected?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'overall',
      label: 'Overall publishing experience',
      prompt: 'How would you rate the overall publishing experience?',
      type: 'rating',
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: 'recommend',
      label: 'Likelihood to recommend J Merrill Publishing',
      prompt: 'How likely are you to recommend J Merrill Publishing?',
      type: 'nps',
      min: 0,
      max: 10,
      required: true,
    },
    {
      id: 'open_feedback',
      label: 'Open feedback',
      prompt: 'What would you like us to know about your publishing experience?',
      type: 'text',
      maxLength: 1200,
      required: false,
    },
  ],
} as const

export type AuthorExperienceQuestion = (typeof PUBLISHING_AUTHOR_EXPERIENCE_SURVEY.questions)[number]
export type AuthorExperienceQuestionId = AuthorExperienceQuestion['id']
