"use strict";

const POLICY_STATUS = Object.freeze({
  CANON: "CANON",
  CANON_CANDIDATE: "CANON-CANDIDATE"
});

const DECISION = Object.freeze({
  ALLOW: "ALLOW",
  ALLOW_WITH_DEFAULT: "ALLOW_WITH_DEFAULT",
  HUMAN_GATE: "HUMAN_GATE",
  EXTERNAL_DEPENDENCY: "EXTERNAL_DEPENDENCY",
  DENY: "DENY",
  LEGACY_RECONCILIATION_ONLY: "LEGACY_RECONCILIATION_ONLY"
});

const LEGACY_SYSTEM_STATE = Object.freeze({
  ACTIVE_CANONICAL: "ACTIVE_CANONICAL",
  GRANDFATHERED_ACTIVE: "GRANDFATHERED_ACTIVE",
  READ_ONLY_EVIDENCE: "READ_ONLY_EVIDENCE",
  MIGRATION_REQUIRED: "MIGRATION_REQUIRED",
  PROHIBITED_FOR_NEW_WORK: "PROHIBITED_FOR_NEW_WORK"
});

const PUBLISHING_COMMUNICATION_CANON = Object.freeze({
  from: "publishing@email.jmerrill.one",
  replyTo: "publishing@jmerrill.one",
  cc: "publishing@jmerrill.one",
  format: "HTML"
});

const INTERNAL_AUTHOR_ARTIFACT_PATTERNS = Object.freeze([
  /\bGenerated by JMI Automation\b/i,
  /\bGenerated by JM1 Automation\b/i,
  /\bDataverse\b/i,
  /\bexecution log\b/i,
  /\bworkflow record\b/i,
  /\bcorrelation\s*id\b/i,
  /\bcorrelationId\b/i,
  /\bartifact\s*id\b/i,
  /\bartifactId\b/i,
  /\bchecksum\b/i,
  /\bsha256\b/i,
  /\bpackage manifest\b/i,
  /\bgovernance heading\b/i,
  /\bJ[0-8]\b/,
  /\bAUTHOR_REVIEW_RESPONSE\b/,
  /\bDEVELOPMENTAL_EDITING\b/,
  /\bLINE_EDITING\b/,
  /\bCOPYEDITING\b/,
  /\bPROOFREADING\b/
]);

const NON_RELEASE_INTENTS = new Set([
  "COMMISSIONING",
  "INTERNAL",
  "PROTOTYPE",
  "PROOF",
  "ARCHIVAL",
  "NON_RELEASE",
  "ARCHIVAL_NON_RELEASE"
]);

const EDITORIAL_SEQUENCE = Object.freeze([
  "EDITORIAL_REVIEW",
  "DEVELOPMENTAL_EDITING",
  "LINE_EDITING",
  "COPYEDITING",
  "PROOFREADING"
]);

const POLICY_REGISTRY = Object.freeze([
  Object.freeze({
    policyId: "JMP-PAYMENT-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Publishing payment",
    enforcementClass: "PRE_MUTATION_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1 / Publishing commercial authority",
    resolver: "resolvePaymentAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-COMMUNICATION-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Publishing communication",
    enforcementClass: "PRE_SEND_HARD_GATE",
    canonSource: "JM1 Enterprise Communication Standard v1.0 / Microsoft-first communications evidence routing",
    resolver: "resolveCommunicationAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-AUTHOR-TITLE-IDENTITY-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Author/title identity",
    enforcementClass: "PRE_MUTATION_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1",
    resolver: "resolveIdentityAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-AUTHOR-FACING-ARTIFACT-SAFETY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Author-facing artifact safety",
    enforcementClass: "PRE_SEND_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1",
    resolver: "resolveArtifactAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-ARTIFACT-SUPERSESSION-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Artifact authority",
    enforcementClass: "PRE_MUTATION_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1",
    resolver: "resolveArtifactSupersessionAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-EDITORIAL-GATE-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Editorial stage authority",
    enforcementClass: "PRE_WORKER_HARD_GATE",
    canonSource: "JMP Editorial Cadence Doctrine v1.0 / Slice 3 PF state machine",
    resolver: "resolveEditorialStageAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-PUBLICATION-INTENT-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Publication intent",
    enforcementClass: "PRE_PRODUCTION_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1 / Target Architecture v1.0",
    resolver: "resolvePublicationIntentAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-PRODUCTION-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Production authority",
    enforcementClass: "PRE_PRODUCTION_HARD_GATE",
    canonSource: "PUB-STD-Onboarding-First-Production-Authority",
    resolver: "resolveProductionAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-BLOCK05-PRODUCTION-COMMISSIONING-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Block 05 production lifecycle",
    enforcementClass: "PRE_PRODUCTION_AND_CERTIFICATION_HARD_GATE",
    canonSource: "JMP Block 05 Production Operating System / JM1 Canon Enforcement & Runtime Policy Layer v1",
    resolver: "resolveBlock05ProductionAuthority",
    effectiveDate: "2026-08-26",
    supersedes: ["JM1 Production Pipeline v2.0 distribution-readiness-as-production-completion semantics"],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-DISTRIBUTION-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Distribution authority",
    enforcementClass: "PRE_DISTRIBUTION_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1 / Publication intent authority",
    resolver: "resolveDistributionAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-CADENCE-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Editorial cadence",
    enforcementClass: "PRE_AUTHOR_RELEASE_HARD_GATE",
    canonSource: "JMP Editorial Cadence Doctrine v1.0",
    resolver: "resolveCadenceAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-WAITING-ON-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Waiting-on classification",
    enforcementClass: "READ_MODEL_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1",
    resolver: "resolveWaitingOnAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  }),
  Object.freeze({
    policyId: "JMP-LEGACY-ROUTING-AUTHORITY-v1.0",
    version: "1.0",
    status: POLICY_STATUS.CANON,
    domain: "Legacy system routing",
    enforcementClass: "PRE_MUTATION_HARD_GATE",
    canonSource: "JM1 Canon Enforcement & Runtime Policy Layer v1",
    resolver: "resolveLegacySystemAuthority",
    effectiveDate: "2026-08-25",
    supersedes: [],
    ownerAuthority: "Jackie Smith, Jr. — Governance Authority"
  })
]);

const POLICY_BY_RESOLVER = Object.freeze(Object.fromEntries(POLICY_REGISTRY.map((row) => [row.resolver, row])));

function normalizeString(value) {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeKey(value) {
  return normalizeString(value).toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function normalizeEmail(value) {
  return normalizeString(value).toLowerCase();
}

function asArray(value) {
  if (Array.isArray(value)) return value;
  if (value === undefined || value === null) return [];
  return [value];
}

function uniqueNormalizedEmails(value) {
  return Array.from(new Set(asArray(value).map(normalizeEmail).filter(Boolean)));
}

function policyFor(resolver) {
  return POLICY_BY_RESOLVER[resolver] || {
    policyId: "JM1-UNKNOWN-POLICY",
    version: "0.0",
    status: "UNKNOWN",
    domain: "unknown",
    enforcementClass: "UNKNOWN",
    canonSource: "UNKNOWN",
    resolver,
    effectiveDate: null,
    supersedes: [],
    ownerAuthority: "UNKNOWN"
  };
}

function decision({ resolver, decision, reason, sourceRecord = null, evidence = [], overrideAllowed = false, overrideRequired = false, overrideAuthority = null, legacyAllowed = false, mutationAllowed = false, extra = {} }) {
  const policy = policyFor(resolver);
  return Object.freeze({
    POLICY: policy.policyId,
    POLICY_VERSION: policy.version,
    DECISION: decision,
    AUTHORITY_SOURCE: policy.canonSource,
    SOURCE_RECORD: sourceRecord,
    EVIDENCE: Object.freeze(asArray(evidence).filter(Boolean)),
    REASON: reason,
    OVERRIDE_ALLOWED: overrideAllowed,
    OVERRIDE_REQUIRED: overrideRequired,
    OVERRIDE_AUTHORITY: overrideAuthority,
    LEGACY_ALLOWED: legacyAllowed,
    MUTATION_ALLOWED: mutationAllowed,
    ...extra
  });
}

function allow(resolver, reason, extra = {}) {
  return decision({ resolver, decision: DECISION.ALLOW, reason, mutationAllowed: true, ...extra });
}

function deny(resolver, reason, extra = {}) {
  return decision({ resolver, decision: DECISION.DENY, reason, mutationAllowed: false, ...extra });
}

function humanGate(resolver, reason, extra = {}) {
  return decision({ resolver, decision: DECISION.HUMAN_GATE, reason, mutationAllowed: false, overrideRequired: true, overrideAuthority: "Jackie Smith, Jr. or formally recorded Dataverse delegation", ...extra });
}

function legacyOnly(resolver, reason, extra = {}) {
  return decision({ resolver, decision: DECISION.LEGACY_RECONCILIATION_ONLY, reason, mutationAllowed: false, legacyAllowed: true, ...extra });
}

function assertPolicyAllows(result) {
  if (!result || result.MUTATION_ALLOWED !== true || result.DECISION !== DECISION.ALLOW) {
    const err = new Error(`CANON_POLICY_BLOCKED:${result?.POLICY || "UNKNOWN"}:${result?.REASON || "UNKNOWN"}`);
    err.safeCode = "CANON_POLICY_BLOCKED";
    err.policyDecision = result || null;
    throw err;
  }
  return true;
}

function resolvePaymentAuthority(input = {}) {
  const resolver = "resolvePaymentAuthority";
  const processor = normalizeKey(input.processor || input.paymentProcessor || input.provider || "STRIPE");
  const system = normalizeKey(input.system || input.paymentSystem || processor);
  const context = normalizeKey(input.context || input.workType || "NEW_PUBLISHING_TRANSACTION");
  const sourceRecord = normalizeString(input.sourceRecord || input.opportunityId || input.invoiceId || input.paymentId) || null;
  if (processor === "STRIPE" || system === "STRIPE") {
    return allow(resolver, "New Publishing commercial mutations resolve to Stripe authority.", {
      sourceRecord,
      evidence: ["Stripe is canonical payment processor for new Publishing commercial transactions."],
      extra: { processor: "STRIPE", legacySystemState: LEGACY_SYSTEM_STATE.ACTIVE_CANONICAL }
    });
  }
  if (processor === "MOONCLERK" || system === "MOONCLERK") {
    if (context === "LEGACY_RECONCILIATION" || input.grandfathered === true) {
      return legacyOnly(resolver, "MoonClerk is allowed only as grandfathered/legacy payment evidence; no new Publishing payment mutation may route there.", {
        sourceRecord,
        evidence: ["MoonClerk real historical payments remain evidence and may be reconciled without refund/recharge."],
        extra: { processor: "MOONCLERK", legacySystemState: LEGACY_SYSTEM_STATE.GRANDFATHERED_ACTIVE }
      });
    }
    return deny(resolver, "MoonClerk is prohibited for new Publishing payment work; no fallback from Stripe is allowed.", {
      sourceRecord,
      evidence: ["Payment authority: Stripe for new work; MoonClerk legacy reconciliation only."],
      extra: { processor: "MOONCLERK", violationEvent: "PAYMENT_PROCESSOR_CANON_VIOLATION", legacySystemState: LEGACY_SYSTEM_STATE.PROHIBITED_FOR_NEW_WORK }
    });
  }
  return deny(resolver, "Payment processor authority is not recognized for Publishing commercial mutation.", {
    sourceRecord,
    evidence: [`Observed processor: ${processor || "MISSING"}`],
    extra: { processor: processor || null, violationEvent: "PAYMENT_PROCESSOR_CANON_VIOLATION" }
  });
}

function resolveCommunicationAuthority(input = {}) {
  const resolver = "resolveCommunicationAuthority";
  const from = normalizeEmail(input.from || input.senderAddress);
  const replyTo = normalizeEmail(input.replyTo || asArray(input.replyTo)[0]?.address);
  const to = uniqueNormalizedEmails(input.to || input.recipients?.to?.map((r) => r.address));
  const cc = uniqueNormalizedEmails(input.cc || input.recipients?.cc?.map((r) => r.address));
  const bcc = uniqueNormalizedEmails(input.bcc || input.recipients?.bcc?.map((r) => r.address));
  const html = normalizeString(input.html || input.content?.html);
  const format = normalizeKey(input.format || (html ? "HTML" : "PLAIN_TEXT_ONLY"));
  const sourceRecord = normalizeString(input.sourceRecord || input.intakeReferenceCode || input.diagnosticId) || null;
  if (from !== PUBLISHING_COMMUNICATION_CANON.from) {
    return deny(resolver, "Publishing author-facing email sender is not canonical.", { sourceRecord, evidence: [`from=${from || "MISSING"}`], extra: { violationEvent: "COMMUNICATION_CANON_VIOLATION" } });
  }
  if (replyTo !== PUBLISHING_COMMUNICATION_CANON.replyTo) {
    return deny(resolver, "Publishing author-facing email Reply-To is not canonical.", { sourceRecord, evidence: [`replyTo=${replyTo || "MISSING"}`], extra: { violationEvent: "COMMUNICATION_CANON_VIOLATION" } });
  }
  if (!to.includes(PUBLISHING_COMMUNICATION_CANON.cc) && !cc.includes(PUBLISHING_COMMUNICATION_CANON.cc)) {
    return deny(resolver, "Publishing visibility CC is missing.", { sourceRecord, evidence: [`cc=${cc.join(",") || "NONE"}`], extra: { violationEvent: "COMMUNICATION_CANON_VIOLATION" } });
  }
  if (bcc.includes(PUBLISHING_COMMUNICATION_CANON.cc)) {
    return deny(resolver, "Publishing visibility copy must be CC, not BCC.", { sourceRecord, evidence: ["publishing@jmerrill.one present in BCC"], extra: { violationEvent: "COMMUNICATION_CANON_VIOLATION" } });
  }
  if (format !== "HTML" || !html) {
    return deny(resolver, "Publishing author-facing email must render canonical HTML; plain-text-only is not allowed.", { sourceRecord, evidence: [`format=${format}`], extra: { violationEvent: "COMMUNICATION_CANON_VIOLATION" } });
  }
  if (from.includes("noreply") || replyTo.includes("noreply")) {
    return deny(resolver, "NoReply author-facing Publishing communication is prohibited.", { sourceRecord, evidence: [`from=${from}`, `replyTo=${replyTo}`], extra: { violationEvent: "COMMUNICATION_CANON_VIOLATION" } });
  }
  return allow(resolver, "Publishing communication authority resolved.", {
    sourceRecord,
    evidence: ["FROM/REPLY-TO/CC/HTML match Publishing communication canon."],
    extra: { canon: PUBLISHING_COMMUNICATION_CANON }
  });
}

function resolveIdentityAuthority(input = {}) {
  const resolver = "resolveIdentityAuthority";
  const authorName = normalizeString(input.authorName || input.author);
  const title = normalizeString(input.title || input.projectTitle);
  const authorId = normalizeString(input.authorId || input.contactId);
  const titleId = normalizeString(input.titleId);
  const opportunityId = normalizeString(input.opportunityId);
  const intakeReferenceCode = normalizeString(input.intakeReferenceCode);
  const sourceRecord = opportunityId || titleId || intakeReferenceCode || null;
  if (/atta darko/i.test(authorName) && /indomitable/i.test(title)) {
    return deny(resolver, "Author/title identity mismatch: Indomitable must not render or mutate as Atta Darko.", {
      sourceRecord,
      evidence: [`author=${authorName}`, `title=${title}`],
      extra: { violationEvent: "AUTHOR_TITLE_IDENTITY_CANON_VIOLATION" }
    });
  }
  if (!authorName || !title) {
    return deny(resolver, "Author and title/project identity must both be known before material mutation or author-facing send.", {
      sourceRecord,
      evidence: [`author=${authorName || "MISSING"}`, `title=${title || "MISSING"}`],
      extra: { violationEvent: "AUTHOR_TITLE_IDENTITY_CANON_VIOLATION" }
    });
  }
  if (!authorId && !opportunityId && !intakeReferenceCode) {
    return deny(resolver, "Identity requires at least one canonical Contact, Opportunity, or Intake relationship.", {
      sourceRecord,
      evidence: ["contact/opportunity/intake relationship missing"],
      extra: { violationEvent: "AUTHOR_TITLE_IDENTITY_CANON_VIOLATION" }
    });
  }
  return allow(resolver, "Author/title identity authority resolved.", {
    sourceRecord,
    evidence: [`author=${authorName}`, `title=${title}`, authorId ? `authorId=${authorId}` : null, opportunityId ? `opportunityId=${opportunityId}` : null, intakeReferenceCode ? `intake=${intakeReferenceCode}` : null]
  });
}

function resolveArtifactAuthority(input = {}) {
  const resolver = "resolveArtifactAuthority";
  const values = asArray(input.values).concat([input.text, input.html, input.bodyText]).map(normalizeString).filter(Boolean);
  const joined = values.join("\n");
  const sourceRecord = normalizeString(input.sourceRecord || input.artifactId) || null;
  const hit = INTERNAL_AUTHOR_ARTIFACT_PATTERNS.find((pattern) => pattern.test(joined));
  if (hit) {
    return deny(resolver, "Author-facing artifact contains internal-only metadata or stage vocabulary.", {
      sourceRecord,
      evidence: [`pattern=${hit}`],
      extra: { violationEvent: "AUTHOR_ARTIFACT_SAFETY_VIOLATION" }
    });
  }
  return allow(resolver, "Author-facing artifact safety resolved.", {
    sourceRecord,
    evidence: ["Positive safe-schema scan found no internal metadata leakage."]
  });
}

function resolveArtifactSupersessionAuthority(input = {}) {
  const resolver = "resolveArtifactSupersessionAuthority";
  const sourceRecord = normalizeString(input.sourceRecord || input.artifactId) || null;
  const status = normalizeKey(input.status || input.artifactStatus);
  if (status === "SUPERSEDED" || input.superseded === true || input.isCurrent === false) {
    return deny(resolver, "Superseded artifacts remain evidence but cannot be current production authority.", {
      sourceRecord,
      evidence: [input.supersededBy ? `supersededBy=${input.supersededBy}` : "artifact marked superseded/not current"],
      extra: { violationEvent: "SUPERSEDED_ARTIFACT_AUTHORITY_VIOLATION" }
    });
  }
  return allow(resolver, "Artifact is eligible as current authority.", { sourceRecord, evidence: ["artifact current/supersession check passed"] });
}

function resolveEditorialStageAuthority(input = {}) {
  const resolver = "resolveEditorialStageAuthority";
  const stageCode = normalizeKey(input.stageCode || input.stage);
  const currentIndex = EDITORIAL_SEQUENCE.indexOf(stageCode);
  const sourceRecord = normalizeString(input.sourceRecord || input.stageId || input.titleId) || null;
  if (currentIndex < 0) {
    return deny(resolver, "Editorial stage is not in canonical sequence.", { sourceRecord, evidence: [`stage=${stageCode || "MISSING"}`], extra: { violationEvent: "EDITORIAL_GATE_BYPASS_ATTEMPT" } });
  }
  if (currentIndex > 0 && input.priorAuthorGateCleared !== true) {
    return deny(resolver, "Downstream editorial worker requires prior author gate clearance.", {
      sourceRecord,
      evidence: [`stage=${stageCode}`, `prior=${EDITORIAL_SEQUENCE[currentIndex - 1]}`],
      extra: { violationEvent: "EDITORIAL_GATE_BYPASS_ATTEMPT" }
    });
  }
  if (input.cadenceEligible === false) {
    return humanGate(resolver, "Cadence hold prevents immediate downstream worker execution.", {
      sourceRecord,
      evidence: [`stage=${stageCode}`, input.scheduledReleaseAt ? `scheduledReleaseAt=${input.scheduledReleaseAt}` : "cadenceEligible=false"],
      extra: { violationEvent: "CADENCE_BYPASS_ATTEMPT" }
    });
  }
  return allow(resolver, "Editorial stage authority resolved.", { sourceRecord, evidence: [`stage=${stageCode}`] });
}

function resolvePublicationIntentAuthority(input = {}) {
  const resolver = "resolvePublicationIntentAuthority";
  const intent = normalizeKey(input.publicationIntent || input.intent || "COMMERCIAL_RELEASE");
  const sourceRecord = normalizeString(input.sourceRecord || input.titleId) || null;
  const nonRelease = NON_RELEASE_INTENTS.has(intent);
  if (nonRelease) {
    return allow(resolver, "Non-release/commissioning publication intent resolved; commercial metadata gates are not required.", {
      sourceRecord,
      evidence: [`publicationIntent=${intent}`],
      extra: {
        publicationIntent: intent,
        isbnRequired: false,
        barcodeRequired: false,
        distributionRequired: false,
        publicationLaunchRequired: false
      }
    });
  }
  return allow(resolver, "Commercial-release publication intent resolved; commercial metadata gates remain required.", {
    sourceRecord,
    evidence: [`publicationIntent=${intent}`],
    extra: {
      publicationIntent: intent,
      isbnRequired: true,
      barcodeRequired: true,
      distributionRequired: true,
      publicationLaunchRequired: true
    }
  });
}

function resolveProductionAuthority(input = {}) {
  const resolver = "resolveProductionAuthority";
  const sourceRecord = normalizeString(input.sourceRecord || input.titleId || input.taskId) || null;
  const missing = [];
  if (!normalizeString(input.trimSize)) missing.push("TRIM_SIZE");
  if (!Number.isInteger(Number(input.pageCount)) || Number(input.pageCount) <= 0) missing.push("FINAL_PAGE_COUNT");
  if (!normalizeString(input.imprint)) missing.push("IMPRINT");
  if (!normalizeString(input.backCoverCopy)) missing.push("BACK_COVER_COPY");
  if (!asArray(input.sourceAssets).some((asset) => normalizeKey(asset?.type) === "FRONT_COVER")) missing.push("FRONT_COVER_ASSET");
  const intent = resolvePublicationIntentAuthority(input);
  if (intent.isbnRequired && !normalizeString(input.isbn)) missing.push("ISBN");
  if (intent.barcodeRequired && !normalizeString(input.barcode)) missing.push("BARCODE");
  if (intent.distributionRequired && !normalizeString(input.distributionPath)) missing.push("DISTRIBUTION_PATH");
  if (missing.length) {
    return deny(resolver, "Production mutation is missing required canonical inputs.", {
      sourceRecord,
      evidence: missing,
      extra: { missing, violationEvent: "PRODUCTION_AUTHORITY_VIOLATION" }
    });
  }
  return allow(resolver, "Production authority resolved.", {
    sourceRecord,
    evidence: ["trim/page count/imprint/back-cover/source assets/publication intent resolved"],
    extra: { publicationIntent: intent.publicationIntent }
  });
}

function resolveBlock05ProductionAuthority(input = {}) {
  const resolver = "resolveBlock05ProductionAuthority";
  const sourceRecord = normalizeString(input.sourceRecord || input.titleId || input.productionMasterId || input.taskId) || null;
  const missing = [];
  const phase = normalizeKey(input.phase || "FINAL_CERTIFICATION");

  if (phase === "ENTRY") {
    if (input.finalEditorialCertified !== true) missing.push("FINAL_EDITORIAL_CERTIFIED");
    if (input.productionReady !== true) missing.push("PRODUCTION_READY");
    if (!normalizeString(input.finalEditorialManuscriptId || input.finalEditorialManuscript?.artifactId)) missing.push("FINAL_EDITORIAL_MANUSCRIPT");
    if (!normalizeString(input.finalEditorialChecksum || input.finalEditorialManuscript?.checksum)) missing.push("FINAL_EDITORIAL_CHECKSUM");
    if (input.editorialApprovalsComplete !== true) missing.push("EDITORIAL_APPROVALS_COMPLETE");
    if (input.styleSheetAvailable !== true) missing.push("TITLE_STYLE_SHEET");
    if (input.productionNotesAvailable !== true) missing.push("PRODUCTION_NOTES");
    if (input.activeTitleProject !== true) missing.push("ACTIVE_TITLE_PROJECT");
    if (input.formatEntitlementsResolved !== true) missing.push("PACKAGE_FORMAT_ENTITLEMENTS");
  }

  if (phase === "PRODUCTION_MASTER") {
    if (input.mutateFinalEditorial === true) missing.push("FINAL_EDITORIAL_MANUSCRIPT_IMMUTABLE");
    if (!normalizeString(input.derivedFrom || input.finalEditorialManuscriptId)) missing.push("DERIVED_FROM_FINAL_EDITORIAL_MANUSCRIPT");
    if (!normalizeString(input.sourceChecksum || input.finalEditorialChecksum)) missing.push("SOURCE_CHECKSUM");
  }

  if (phase === "FINAL_CERTIFICATION") {
    if (input.scopeLockComplete !== true) missing.push("PRODUCTION_SCOPE_LOCK");
    if (input.requiredWorkstreamsCertified !== true) missing.push("ALL_REQUIRED_WORKSTREAMS_CERTIFIED");
    if (input.requiredAuthorApprovalsComplete !== true) missing.push("ALL_REQUIRED_AUTHOR_APPROVALS_COMPLETE");
    if (input.technicalValidationsPass !== true) missing.push("ALL_TECHNICAL_VALIDATIONS_PASS");
    if (input.finalArtifactsIdentified !== true) missing.push("FINAL_ARTIFACTS_IDENTIFIED");
    if (input.checksumsVerified !== true) missing.push("CHECKSUMS_VERIFIED");
    if (input.publicationMetadataReady !== true) missing.push("PUBLICATION_METADATA_PACKAGE_READY");
    if (input.accessibilitySatisfiedOrGoverned !== true) missing.push("ACCESSIBILITY_SATISFIED_OR_GOVERNED");
    if (input.crossFormatSynchronizationPass !== true) missing.push("CROSS_FORMAT_SYNCHRONIZATION_PASS");
    if (input.handoffPackageComplete !== true) missing.push("BLOCK06_HANDOFF_PACKAGE");
  }

  if (input.authorDecision && normalizeKey(input.authorDecision) !== "APPROVED") missing.push("AUTHOR_DECISION_NOT_APPROVAL");
  if (input.authorApprovalRequiresArtifactBinding === true && !normalizeString(input.artifactId)) missing.push("AUTHOR_APPROVAL_ARTIFACT_BINDING");
  if (input.authorApprovalTreatedAsTechnicalValidation === true) missing.push("AUTHOR_APPROVAL_NOT_TECHNICAL_VALIDATION");
  if (input.coverMarketabilityTreatedAsTechnicalPass === true) missing.push("COVER_MARKETABILITY_NOT_TECHNICAL_PASS");
  if (input.pageCountChanged === true && input.coverRegenerated !== true) missing.push("COVER_REGENERATION_REQUIRED");
  if (input.productionMasterChanged === true && input.derivedAssetsRevalidated !== true) missing.push("DERIVED_ASSET_REVALIDATION_REQUIRED");
  if (input.unresolvedProductionCorrection === true) missing.push("UNRESOLVED_PRODUCTION_CORRECTION");
  if (asArray(input.attemptedActions).map(normalizeKey).includes("DISTRIBUTION_SUBMISSION")) missing.push("BLOCK05_DISTRIBUTION_SUBMISSION_FORBIDDEN");

  if (missing.length) {
    return deny(resolver, "Block 05 production lifecycle hard gate blocked mutation/certification.", {
      sourceRecord,
      evidence: missing,
      extra: { phase, missing: [...new Set(missing)], violationEvent: "BLOCK05_PRODUCTION_CANON_VIOLATION" }
    });
  }

  return allow(resolver, "Block 05 production lifecycle authority resolved.", {
    sourceRecord,
    evidence: [`phase=${phase}`],
    extra: {
      phase,
      publicationAssetsReadyAllowed: phase === "FINAL_CERTIFICATION"
    }
  });
}

function resolveCadenceAuthority(input = {}) {
  const resolver = "resolveCadenceAuthority";
  const sourceRecord = normalizeString(input.sourceRecord || input.cadenceScheduleId || input.stageId) || null;
  if (input.rush === true && !normalizeString(input.rushApprovedBy) && !normalizeString(input.delegationId)) {
    return humanGate(resolver, "Rush cadence requires Jackie approval or formally recorded delegation.", {
      sourceRecord,
      evidence: ["rush requested without approval/delegation"],
      extra: { violationEvent: "CADENCE_BYPASS_ATTEMPT" }
    });
  }
  if (input.cadenceEligible === false) {
    return humanGate(resolver, "Cadence schedule is not yet eligible for author-facing release or next worker.", {
      sourceRecord,
      evidence: [input.scheduledReleaseAt ? `scheduledReleaseAt=${input.scheduledReleaseAt}` : "cadenceEligible=false"],
      extra: { violationEvent: "CADENCE_BYPASS_ATTEMPT" }
    });
  }
  return allow(resolver, "Cadence authority resolved.", { sourceRecord, evidence: ["cadence eligible or no cadence hold present"] });
}

function resolveWaitingOnAuthority(input = {}) {
  const resolver = "resolveWaitingOnAuthority";
  const waitingOn = normalizeKey(input.waitingOn);
  const sourceRecord = normalizeString(input.sourceRecord || input.titleId || input.stageId) || null;
  if (waitingOn === "WAITING_ON_AUTHOR") {
    if (input.currentAuthorRequestDelivered !== true) {
      return deny(resolver, "WAITING_ON_AUTHOR requires a valid current delivered author request.", {
        sourceRecord,
        evidence: ["current author request absent or undelivered"],
        extra: { correctedWaitingOn: "WAITING_ON_JMP", violationEvent: "WAITING_ON_MISCLASSIFICATION" }
      });
    }
    if (input.unconsumedAuthorResponsePresent === true) {
      return deny(resolver, "WAITING_ON_AUTHOR is invalid when an unconsumed author response already exists.", {
        sourceRecord,
        evidence: ["unconsumed author response present"],
        extra: { correctedWaitingOn: "WAITING_ON_JMP", violationEvent: "WAITING_ON_MISCLASSIFICATION" }
      });
    }
  }
  if (waitingOn === "WAITING_ON_SYSTEM" && !normalizeString(input.systemFailureCode)) {
    return deny(resolver, "WAITING_ON_SYSTEM requires a concrete system failure code.", {
      sourceRecord,
      evidence: ["system failure code missing"],
      extra: { correctedWaitingOn: "WAITING_ON_JMP", violationEvent: "WAITING_ON_MISCLASSIFICATION" }
    });
  }
  return allow(resolver, "Waiting-on authority resolved.", { sourceRecord, evidence: [`waitingOn=${waitingOn || "MISSING"}`] });
}

function resolveLegacySystemAuthority(input = {}) {
  const resolver = "resolveLegacySystemAuthority";
  const system = normalizeKey(input.system);
  const context = normalizeKey(input.context || input.workType);
  const sourceRecord = normalizeString(input.sourceRecord) || null;
  if (system === "MOONCLERK") {
    if (context === "LEGACY_RECONCILIATION" || input.grandfathered === true) {
      return legacyOnly(resolver, "MoonClerk may be read/reconciled for grandfathered active or historical evidence only.", {
        sourceRecord,
        evidence: ["MoonClerk is not active canonical for new Publishing payment work."],
        extra: { legacySystemState: LEGACY_SYSTEM_STATE.GRANDFATHERED_ACTIVE }
      });
    }
    return deny(resolver, "MoonClerk is prohibited for new Publishing work.", {
      sourceRecord,
      evidence: [`context=${context || "MISSING"}`],
      extra: { legacySystemState: LEGACY_SYSTEM_STATE.PROHIBITED_FOR_NEW_WORK, violationEvent: "LEGACY_SYSTEM_ROUTING_VIOLATION" }
    });
  }
  return allow(resolver, "Legacy routing authority resolved.", { sourceRecord, evidence: [`system=${system || "MISSING"}`], extra: { legacySystemState: LEGACY_SYSTEM_STATE.ACTIVE_CANONICAL } });
}

module.exports = {
  DECISION,
  LEGACY_SYSTEM_STATE,
  POLICY_REGISTRY,
  PUBLISHING_COMMUNICATION_CANON,
  assertPolicyAllows,
  resolveArtifactAuthority,
  resolveArtifactSupersessionAuthority,
  resolveCadenceAuthority,
  resolveCommunicationAuthority,
  resolveDistributionAuthority: resolvePublicationIntentAuthority,
  resolveEditorialStageAuthority,
  resolveIdentityAuthority,
  resolveLegacySystemAuthority,
  resolvePaymentAuthority,
  resolveBlock05ProductionAuthority,
  resolveProductionAuthority,
  resolvePublicationIntentAuthority,
  resolveWaitingOnAuthority
};
