"use strict";

const mammoth = require("mammoth");

const POLICY_ID = "JM1-HUMAN-FACING-LAST-MILE-CERTIFICATION-v1";

const INTERNAL_LANGUAGE_PATTERNS = [
  /\bcurrent author-facing files\b/i,
  /\bcurrent publishing stage\b/i,
  /\bproject history\b/i,
  /\bgoverned artifact\b/i,
  /\bartifact\b/i,
  /\bruntime\b/i,
  /\bcorrelation\b/i,
  /\bsystem attention\b/i,
  /\bpackage-grade\b/i,
  /\bexecution state\b/i,
  /\bDataverse\b/i,
  /\bexecution log\b/i,
  /\bworkflow record\b/i
];

const AUTHOR_MANUSCRIPT_BLOCKERS = [
  /\bGenerated by:\s*JM1 Automation\b/i,
  /\bGoverned Developmental Revision Artifact\b/i,
  /\bSource artifact\b/i,
  /\bSource checksum\b/i,
  /\bCorrelation(?: ID)?\b/i,
  /\bextracted word count\b/i,
  /\bextracted paragraph count\b/i,
  /\bpublisher review note\b/i,
  /\bbefore author-facing release\b/i,
  /\bwork queue\b/i,
  /\bexecution metadata\b/i,
  /\bQA evidence\b/i
];

function normalizeText(value) {
  return typeof value === "string" ? value.replace(/\s+/g, " ").trim() : "";
}

function wordCount(text) {
  return (normalizeText(text).match(/\b[\w'’-]+\b/g) || []).length;
}

function headingCount(html) {
  return (String(html || "").match(/<h[1-6]\b/gi) || []).length;
}

function firstName(name) {
  return normalizeText(name).split(/\s+/)[0] || "";
}

function findPatternMatches(text, patterns) {
  return patterns
    .filter((pattern) => pattern.test(text))
    .map((pattern) => pattern.source);
}

function certifyEmailLastMile(input = {}) {
  const html = String(input.htmlBody || "");
  const text = String(input.body || "");
  const combined = `${html}\n${text}`;
  const authorFirstName = firstName(input.authorName);
  const violations = [];
  const warnings = [];

  if (new RegExp(`Good day\\s+${input.authorName || ""},`, "i").test(combined)) {
    violations.push("GREETING_FULL_NAME_WITHOUT_COMMA");
  }
  if (authorFirstName && new RegExp(`Good day\\s+${authorFirstName},`, "i").test(combined)) {
    violations.push("GREETING_MISSING_COMMA_AFTER_GOOD_DAY");
  }
  if (authorFirstName && !new RegExp(`Good day,\\s*${authorFirstName},`, "i").test(combined)) {
    warnings.push("GREETING_NOT_NATURAL_FIRST_NAME_FORM");
  }

  const internalMatches = findPatternMatches(combined, INTERNAL_LANGUAGE_PATTERNS);
  if (internalMatches.length) violations.push(`INTERNAL_LANGUAGE:${internalMatches.join("|")}`);

  const headings = headingCount(html);
  if (headings > 2) violations.push(`ROUTINE_EMAIL_TEMPLATE_BLOAT:${headings}_HEADINGS`);

  if (!/\breply\b/i.test(text)) violations.push("CLEAR_REPLY_ACTION_MISSING");
  if (!/\bnext\b|\bonce we receive\b|\bmove\b/i.test(text)) violations.push("CLEAR_NEXT_STEP_MISSING");
  if (!/J Merrill Publishing/i.test(combined)) violations.push("BRAND_MISSING");
  if (/{{[^}]+}}|\[[A-Z0-9_]+]/.test(combined)) violations.push("BROKEN_PLACEHOLDER");

  return {
    policyId: POLICY_ID,
    decision: violations.length ? "DENY" : warnings.length ? "ALLOW_WITH_WARNING" : "ALLOW",
    commissioningResult: violations.length ? "HUMAN_LAST_MILE_NOT_PROVEN" : "HUMAN_LAST_MILE_PROVEN",
    violations,
    warnings,
    headingCount: headings
  };
}

async function extractDocxText(buffer) {
  const result = await mammoth.extractRawText({ buffer });
  return result.value || "";
}

async function certifyAuthorManuscriptAttachment(input = {}) {
  const fileName = normalizeText(input.fileName);
  const role = normalizeText(input.role);
  const buffer = input.buffer;
  const lower = fileName.toLowerCase();
  const violations = [];
  const warnings = [];

  if (!["editedManuscript", "lineEditedManuscript", "copyeditedManuscript", "proofreadManuscript"].includes(role)) {
    return {
      policyId: POLICY_ID,
      decision: "ALLOW",
      commissioningResult: "HUMAN_LAST_MILE_PROVEN",
      violations,
      warnings,
      inspected: false,
      reason: "NON_MANUSCRIPT_ROLE"
    };
  }

  if (!lower.endsWith(".docx")) {
    violations.push("AUTHOR_MANUSCRIPT_NOT_DOCX");
    return { policyId: POLICY_ID, decision: "DENY", commissioningResult: "HUMAN_LAST_MILE_NOT_PROVEN", violations, warnings };
  }

  const text = await extractDocxText(buffer);
  const normalized = normalizeText(text);
  const words = wordCount(normalized);
  const internalMatches = findPatternMatches(normalized, AUTHOR_MANUSCRIPT_BLOCKERS);
  if (internalMatches.length) violations.push(`INTERNAL_METADATA_LEAK:${internalMatches.join("|")}`);
  if (words < 5000) violations.push(`MANUSCRIPT_WORD_COUNT_TOO_LOW:${words}`);
  if (!normalized.slice(0, 1000).trim()) violations.push("OPENING_CONTENT_MISSING");
  if (!normalized.slice(-1000).trim()) violations.push("ENDING_CONTENT_MISSING");
  if (/^\s*(Generated by:|Governed|Source artifact|Correlation)/i.test(text)) violations.push("INTERNAL_COVER_PAGE_PRESENT");

  return {
    policyId: POLICY_ID,
    decision: violations.length ? "DENY" : warnings.length ? "ALLOW_WITH_WARNING" : "ALLOW",
    commissioningResult: violations.length ? "HUMAN_LAST_MILE_NOT_PROVEN" : "HUMAN_LAST_MILE_PROVEN",
    violations,
    warnings,
    inspected: true,
    wordCount: words,
    openingSample: normalized.slice(0, 160),
    endingSample: normalized.slice(-160)
  };
}

module.exports = {
  POLICY_ID,
  certifyAuthorManuscriptAttachment,
  certifyEmailLastMile,
  extractDocxText
};
