<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>plugin</AssemblyName>
    <RootNamespace>plugin</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(JMP_TRANSITION_SIGNING_KEY_PATH)</AssemblyOriginatorKeyFile>
    <AssemblyVersion>1.0.0.3</AssemblyVersion>
    <FileVersion>1.0.0.4</FileVersion>
    <Version>1.0.0.4</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.59" PrivateAssets="All" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
