import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync } from 'node:child_process'
import test from 'node:test'

const python = process.env.PYTHON || '/Users/jmerrillone/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3'
const script = new URL('./author_review_preparation.py', import.meta.url).pathname

function makeFixture(path) {
  execFileSync(python, ['-c', `
from docx import Document
doc=Document()
doc.add_paragraph('Generated by: JM1 Automation')
doc.add_paragraph('Developmentally Edited Manuscript - Developmental Editing - The General\\'s Will and Last Testament')
doc.add_paragraph('Stage: DEVELOPMENTAL_EDITING')
doc.add_paragraph('Source artifact: f573362c-1c84-f111-ab0f-7c1e525b15c2')
doc.add_paragraph('Source checksum: 43072232c21939b349d5b44d45967a0154e8ccfd57e39ddc1ea7261dddf81171')
doc.add_paragraph('Correlation: EDITORIAL-RUNTIME-TIMER-2026-07-21T02:20:00.138Z')
doc.add_paragraph('Current Execution State')
doc.add_paragraph('EXECUTING')
doc.add_paragraph('THE GENERAL\\'S WILL AND LAST TESTAMENT')
doc.add_paragraph('The visible manuscript text remains. Publisher review note P43: Confirm rights, permissions, or legal posture before author-facing release.')
doc.add_paragraph('Another paragraph. Developmental note P237: Review sentence length for clarity during line editing; preserve intentional cadence where it is part of the author style.')
doc.save(r'''${path}''')
`])
}

function makeCommentFixture(path) {
  execFileSync(python, ['-c', `
from docx import Document
doc=Document()
p=doc.add_paragraph('The visible manuscript text remains.')
comment=doc.add_comment(p.runs, text='Author-facing editorial question: Please confirm this detail.', author='J Merrill Publishing')
doc.save(r'''${path}''')
`])
}

test('preparation removes visible internal metadata and publisher-only notes', () => {
  const dir = mkdtempSync(join(tmpdir(), 'program-008-'))
  const input = join(dir, 'internal.docx')
  const output = join(dir, 'author.docx')
  makeFixture(input)

  const prep = JSON.parse(execFileSync(python, [script, 'prepare', input, output], { encoding: 'utf8' }))
  assert.equal(prep.status, 'PASS')
  assert.ok(prep.removed_paragraphs >= 8)
  assert.ok(prep.cleaned_inline_fragments >= 2)

  const validation = JSON.parse(execFileSync(python, [script, 'validate', output], { encoding: 'utf8' }))
  assert.equal(validation.status, 'PASS')
  assert.equal(validation.internal_comments, 0)

  const documentXml = execFileSync('unzip', ['-p', output, 'word/document.xml'], { encoding: 'utf8' })
  assert.match(documentXml, /The visible manuscript text remains/)
  assert.doesNotMatch(documentXml, /JM1 Automation|Developmentally Edited Manuscript|Source artifact|Source checksum|Correlation|Publisher review note|Developmental note P237|EXECUTING/)
})

test('validation fails closed when internal markers remain', () => {
  const dir = mkdtempSync(join(tmpdir(), 'program-008-'))
  const input = join(dir, 'dirty.docx')
  makeFixture(input)
  let failed = false
  try {
    execFileSync(python, [script, 'validate', input], { encoding: 'utf8', stdio: 'pipe' })
  } catch (error) {
    failed = true
    const output = error.stdout.toString()
    assert.match(output, /AUTOMATION_METADATA|PUBLISHER_NOTES|CORRELATION_IDS|ARTIFACT_IDS|CHECKSUMS|EXECUTION_STATE/)
  }
  assert.equal(failed, true)
})

test('preparation preserves author-facing editorial comments', () => {
  const dir = mkdtempSync(join(tmpdir(), 'program-008-'))
  const input = join(dir, 'commented.docx')
  const output = join(dir, 'author.docx')
  makeCommentFixture(input)

  const prep = JSON.parse(execFileSync(python, [script, 'prepare', input, output], { encoding: 'utf8' }))
  assert.equal(prep.status, 'PASS')

  const commentsXml = execFileSync('unzip', ['-p', output, 'word/comments.xml'], { encoding: 'utf8' })
  assert.match(commentsXml, /Author-facing editorial question/)

  const validation = JSON.parse(execFileSync(python, [script, 'validate', output], { encoding: 'utf8' }))
  assert.equal(validation.status, 'PASS')
  assert.equal(validation.internal_comments, 0)
})

test('standard declares package boundary and prohibited internal material', () => {
  const standard = readFileSync(new URL('../docs/doctrine/JMP-Author-Review-Preparation-Standard-v1.0.md', import.meta.url), 'utf8')
  assert.match(standard, /Internal Editorial Working Manuscript/)
  assert.match(standard, /Author Review Manuscript/)
  assert.match(standard, /must never contain/)
  assert.match(standard, /automation metadata/)
  assert.match(standard, /publisher-only notes/)
  assert.match(standard, /Editorial Review Guide PDF/)
  assert.match(standard, /Portal access remains optional/)
})
