#!/usr/bin/env python3
"""Prepare internal editorial DOCX files for author review.

Engine: AuthorReviewPreparationService
Reusable? Y
Stage-specific exception? N
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable
from xml.etree import ElementTree as ET


NS = {
    "w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
    "rel": "http://schemas.openxmlformats.org/package/2006/relationships",
    "ct": "http://schemas.openxmlformats.org/package/2006/content-types",
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
}

ET.register_namespace("w", NS["w"])
ET.register_namespace("cp", NS["cp"])
ET.register_namespace("dc", NS["dc"])


INTERNAL_PARAGRAPH_PATTERNS = [
    re.compile(r"^\s*(Developmentally Edited|Proofread|Copyedited|Line-Edited)\s+Manuscript\s+-\s+.+$", re.I),
    re.compile(r"^\s*Author Review Preparation\s+Artifact\s+-\s+.+$", re.I),
    re.compile(r"^\s*Generated by:\s*JM1 Automation\s*$", re.I),
    re.compile(r"^\s*Stage:\s*[A-Z0-9_ -]+\s*$", re.I),
    re.compile(r"^\s*Generated at:\s*\d{4}-\d{2}-\d{2}T", re.I),
    re.compile(r"^\s*Source artifact:\s*[0-9a-f-]{20,}\s*$", re.I),
    re.compile(r"^\s*Source checksum:\s*[0-9a-f]{32,}\s*$", re.I),
    re.compile(r"^\s*Correlation:\s*[A-Z0-9_:.-]+\s*$", re.I),
    re.compile(r"^\s*Extracted word count:\s*\d+\s*$", re.I),
    re.compile(r"^\s*Extracted paragraph count:\s*\d+\s*$", re.I),
    re.compile(r"^\s*Governed Developmental Revision Artifact\s*$", re.I),
    re.compile(r"^\s*Developmental Findings\s*$", re.I),
    re.compile(r"^\s*Manuscript Revision Layer\s*$", re.I),
    re.compile(r"^\s*Developmental Editing Output\s*$", re.I),
    re.compile(r"^\s*Developmental Work Queue\b.*$", re.I),
    re.compile(r"^\s*Line-Level Deferral Queue\b.*$", re.I),
    re.compile(r"^\s*Continuity / Repetition Candidates\b.*$", re.I),
    re.compile(r"^\s*Change Ledger\s*$", re.I),
    re.compile(r"^\s*QA Evidence\s*$", re.I),
    re.compile(r"^\s*Current Execution State\s*$", re.I),
    re.compile(r"^\s*EXECUTING\s*$", re.I),
    re.compile(r"^\s*Source Sample Used For QA\s*$", re.I),
    re.compile(r"^\s*This package-grade revision artifact preserves\b.*$", re.I),
    re.compile(r"^\s*The manuscript contains pacing and readability candidates\b.*$", re.I),
    re.compile(r"^\s*Developmental Editing has begun against the governed source manuscript\b.*$", re.I),
    re.compile(r"^\s*Source checksum matched\b.*$", re.I),
    re.compile(r"^\s*No author-facing package released\b.*$", re.I),
    re.compile(r"^\s*No stage advancement occurred\b.*$", re.I),
    re.compile(r"^\s*Working manuscript pass opened under JM1 Automation\b.*$", re.I),
    re.compile(r"^\s*Source manuscript checksum validated\b.*$", re.I),
    re.compile(r"^\s*Structural/readability candidates extracted\b.*$", re.I),
    re.compile(r"^\s*\|.*\|\s*$"),
]

INLINE_INTERNAL_PATTERNS = [
    re.compile(r"\s*Publisher review note P\d+:\s*[^.?!]*(?:author-facing release|legal posture|rights|permissions)[^.?!]*[.?!]?", re.I),
    re.compile(r"\s*Developmental note P\d+:\s*Review sentence length[^.?!]*[.?!]?", re.I),
    re.compile(r"\s*EDITORIAL-RUNTIME-[A-Z0-9:.-]+", re.I),
    re.compile(r"\s*[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I),
    re.compile(r"\s*[0-9a-f]{64}", re.I),
]

VALIDATION_PATTERNS = {
    "publisher_notes": re.compile(r"\b(Publisher review note|Developmental note P\d+)\b", re.I),
    "automation_metadata": re.compile(r"\b(Generated by:\s*JM1 Automation|Generated at:|JM1 Automation|automation metadata)\b", re.I),
    "correlation_ids": re.compile(r"\b(Correlation:|EDITORIAL-RUNTIME-|correlation id)\b", re.I),
    "artifact_ids": re.compile(r"\b(Source artifact:|artifact id|source artifact)\b", re.I),
    "checksums": re.compile(r"\b(Source checksum:|checksum)\b|[0-9a-f]{64}", re.I),
    "execution_state": re.compile(r"\b(Current Execution State|EXECUTING)\b", re.I),
    "visible_qa_markers": re.compile(r"\b(QA Evidence|Source Sample Used For QA|Change Ledger|Line-Level Deferral Queue|Continuity / Repetition Candidates)\b", re.I),
}


@dataclass
class PreparationResult:
    input: str
    output: str
    status: str
    removed_paragraphs: int
    cleaned_inline_fragments: int
    removed_comment_parts: int
    input_sha256: str
    output_sha256: str
    output_size: int


@dataclass
class ValidationResult:
    file: str
    status: str
    opens: str
    corruption: str
    internal_comments: int
    track_changes: str
    checks: dict[str, int]
    blockers: list[str]
    page_count: int | None = None


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def text_of(element: ET.Element) -> str:
    return "".join(t.text or "" for t in element.findall(".//w:t", NS))


def set_paragraph_text(paragraph: ET.Element, text: str) -> None:
    texts = paragraph.findall(".//w:t", NS)
    if not texts:
        return
    texts[0].text = text
    for node in texts[1:]:
        node.text = ""


def should_remove_paragraph(text: str) -> bool:
    stripped = text.strip()
    if not stripped:
        return False
    return any(pattern.search(stripped) for pattern in INTERNAL_PARAGRAPH_PATTERNS)


def clean_inline(text: str) -> tuple[str, int]:
    cleaned = text
    count = 0
    for pattern in INLINE_INTERNAL_PATTERNS:
        cleaned, n = pattern.subn("", cleaned)
        count += n
    cleaned = re.sub(r" {2,}", " ", cleaned)
    return cleaned.strip() if text.strip() == text else cleaned, count


def remove_element(element: ET.Element) -> None:
    parent = None
    for candidate in element.iter():
        # ElementTree does not expose parent pointers.
        pass


def parents(root: ET.Element) -> dict[int, ET.Element]:
    return {id(child): parent for parent in root.iter() for child in parent}


def clean_document_xml(path: Path) -> tuple[int, int]:
    tree = ET.parse(path)
    root = tree.getroot()
    removed_paragraphs = 0
    cleaned_inline = 0
    parent_map = parents(root)

    for paragraph in list(root.findall(".//w:p", NS)):
        paragraph_text = text_of(paragraph)
        if should_remove_paragraph(paragraph_text):
            parent = parent_map.get(id(paragraph))
            if parent is not None:
                parent.remove(paragraph)
                removed_paragraphs += 1
            continue
        cleaned, count = clean_inline(paragraph_text)
        if count:
            set_paragraph_text(paragraph, cleaned)
            cleaned_inline += count

    tree.write(path, encoding="utf-8", xml_declaration=True)
    return removed_paragraphs, cleaned_inline


def scrub_core_properties(path: Path) -> None:
    if not path.exists():
        return
    tree = ET.parse(path)
    root = tree.getroot()
    for tag in ("creator", "lastModifiedBy"):
        node = root.find(f".//dc:{tag}", NS)
        if node is not None and node.text and "JM1" in node.text:
            node.text = "J Merrill Publishing"
    tree.write(path, encoding="utf-8", xml_declaration=True)


def prepare_docx(input_path: Path, output_path: Path) -> PreparationResult:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="author-review-prep-") as tmp:
        tmp_path = Path(tmp)
        with zipfile.ZipFile(input_path) as archive:
            archive.extractall(tmp_path)
        removed_paragraphs, cleaned_inline = clean_document_xml(tmp_path / "word" / "document.xml")
        scrub_core_properties(tmp_path / "docProps" / "core.xml")
        removed_comment_parts = 0
        replacement_parts = {
            "word/document.xml": (tmp_path / "word" / "document.xml").read_bytes(),
            "docProps/core.xml": (tmp_path / "docProps" / "core.xml").read_bytes(),
        }
        with zipfile.ZipFile(input_path) as source, zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as target:
            for info in source.infolist():
                name = info.filename
                if name == "[Content_Types].xml":
                    target.writestr(info, source.read(name))
                    continue
                if name == "word/_rels/document.xml.rels":
                    target.writestr(info, source.read(name))
                    continue
                if name in replacement_parts:
                    target.writestr(info, replacement_parts[name])
                else:
                    target.writestr(info, source.read(name))

    validate_zip(output_path)
    return PreparationResult(
        input=str(input_path),
        output=str(output_path),
        status="PASS",
        removed_paragraphs=removed_paragraphs,
        cleaned_inline_fragments=cleaned_inline,
        removed_comment_parts=removed_comment_parts,
        input_sha256=sha256(input_path),
        output_sha256=sha256(output_path),
        output_size=output_path.stat().st_size,
    )


def validate_zip(path: Path) -> None:
    with zipfile.ZipFile(path) as archive:
        bad = archive.testzip()
    if bad:
        raise ValueError(f"docx_corrupt:{bad}")


def extract_text(path: Path) -> str:
    with zipfile.ZipFile(path) as archive:
        xml = archive.read("word/document.xml")
    root = ET.fromstring(xml)
    chunks = []
    for paragraph in root.findall(".//w:p", NS):
        value = text_of(paragraph).strip()
        if value:
            chunks.append(value)
    return "\n".join(chunks)


def count_internal_comments(path: Path) -> int:
    with zipfile.ZipFile(path) as archive:
        total = 0
        for name in archive.namelist():
            if not (name.startswith("word/comments") and name.endswith(".xml")):
                continue
            xml = archive.read(name).decode("utf-8", errors="ignore")
            total += len(VALIDATION_PATTERNS["publisher_notes"].findall(xml))
            total += len(VALIDATION_PATTERNS["automation_metadata"].findall(xml))
            total += len(VALIDATION_PATTERNS["correlation_ids"].findall(xml))
            total += len(VALIDATION_PATTERNS["artifact_ids"].findall(xml))
            total += len(VALIDATION_PATTERNS["checksums"].findall(xml))
            total += len(VALIDATION_PATTERNS["execution_state"].findall(xml))
            total += len(VALIDATION_PATTERNS["visible_qa_markers"].findall(xml))
        return total


def track_change_state(path: Path) -> str:
    with zipfile.ZipFile(path) as archive:
        xml = archive.read("word/document.xml").decode("utf-8", errors="ignore")
    return "PRESENT" if re.search(r"<w:(ins|del|moveFrom|moveTo)\b", xml) else "NONE"


def page_count_from_pdf(pdf_path: Path) -> int | None:
    if not pdf_path.exists():
        return None
    try:
        output = subprocess.check_output(["pdfinfo", str(pdf_path)], text=True, stderr=subprocess.DEVNULL)
    except Exception:
        return None
    match = re.search(r"^Pages:\s*(\d+)", output, re.M)
    return int(match.group(1)) if match else None


def validate_author_review_docx(path: Path, rendered_pdf: Path | None = None) -> ValidationResult:
    blockers: list[str] = []
    opens = "PASS"
    corruption = "NONE"
    try:
        validate_zip(path)
    except Exception as error:
        opens = "FAIL"
        corruption = str(error)
        blockers.append("DOCX_CORRUPTION")

    text = extract_text(path) if opens == "PASS" else ""
    checks = {name: len(pattern.findall(text)) for name, pattern in VALIDATION_PATTERNS.items()}
    for name, count in checks.items():
        if count:
            blockers.append(name.upper())

    comments = count_internal_comments(path)
    if comments:
        blockers.append("INTERNAL_COMMENTS")

    return ValidationResult(
        file=str(path),
        status="PASS" if not blockers else "FAIL",
        opens=opens,
        corruption=corruption,
        internal_comments=comments,
        track_changes=track_change_state(path),
        checks=checks,
        blockers=blockers,
        page_count=page_count_from_pdf(rendered_pdf) if rendered_pdf else None,
    )


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2), encoding="utf-8")


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare and validate Author Review Manuscript DOCX files.")
    sub = parser.add_subparsers(dest="command", required=True)

    prep = sub.add_parser("prepare")
    prep.add_argument("input", type=Path)
    prep.add_argument("output", type=Path)
    prep.add_argument("--result-json", type=Path)

    val = sub.add_parser("validate")
    val.add_argument("file", type=Path)
    val.add_argument("--rendered-pdf", type=Path)
    val.add_argument("--result-json", type=Path)

    args = parser.parse_args(argv)

    if args.command == "prepare":
        result = prepare_docx(args.input, args.output)
        if args.result_json:
            write_json(args.result_json, asdict(result))
        print(json.dumps(asdict(result), indent=2))
        return 0

    if args.command == "validate":
        result = validate_author_review_docx(args.file, args.rendered_pdf)
        if args.result_json:
            write_json(args.result_json, asdict(result))
        print(json.dumps(asdict(result), indent=2))
        return 0 if result.status == "PASS" else 1

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
