import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import ts from 'typescript'

const source = readFileSync('lib/server/jm1-canon-guard.ts', 'utf8')
const bootstrap = readFileSync('scripts/jm1_bootstrap.mjs', 'utf8')
const js = ts.transpileModule(source, {
  compilerOptions: {
    module: ts.ModuleKind.ES2022,
    target: ts.ScriptTarget.ES2022,
  },
}).outputText
const moduleUrl = `data:text/javascript;base64,${Buffer.from(js).toString('base64')}`
const guard = await import(moduleUrl)

const validPagination = {
  frontMatterFoliosVisible: false,
  firstChapterPageNumber: 1,
  firstChapterRecto: true,
  chapterOpeningHeaderVisible: false,
  chapterOpeningFooterVisible: false,
  chapterOpeningFolioVisible: false,
  continuationPageRunningHeaderPresent: true,
  continuationPageFolioPresent: true,
  laterChapterStarts: [{ chapterLabel: 'Chapter 2', pageSide: 'verso', artificialBlankPageBefore: false }],
}

const cases = [
  {
    id: 'A1',
    fn: guard.enforceA1Renderer,
    pass: { metadata: { standard: 'JM1 Enterprise Communication Standard v1.0', renderer: 'JM1 Enterprise Communication Renderer', qualityGate: 'PASS' } },
    fail: { metadata: { standard: 'legacy', renderer: 'mail-merge', qualityGate: 'PASS' } },
  },
  {
    id: 'A2',
    fn: guard.enforceA2SenderReplyTo,
    pass: { brand: 'publishing', from: 'publishing@email.jmerrill.one', replyTo: 'publishing@jmerrill.one' },
    fail: { brand: 'publishing', from: 'publishing@email.jmerrill.one', replyTo: 'noreply@email.jmerrill.one' },
  },
  {
    id: 'A3',
    fn: guard.enforceA3NoInternalHeadingLeakage,
    pass: { brandName: 'J Merrill Publishing', html: '<div role="banner">J Merrill Publishing</div>', text: 'The Publishing Team\nJ Merrill Publishing, Inc.' },
    fail: { brandName: 'J Merrill Publishing', html: '<h1>J Merrill Publishing</h1>', text: 'J Merrill Publishing' },
  },
  {
    id: 'A4',
    fn: guard.enforceA4AuthorPackageAttachmentSet,
    pass: { attachments: [{ fileName: 'Author Review Manuscript.docx', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }, { fileName: 'Editorial Review Guide.pdf', contentType: 'application/pdf' }] },
    fail: { attachments: [{ fileName: 'Author Review Manuscript.docx', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }, { fileName: 'Editorial Review Guide.txt', contentType: 'text/plain' }] },
  },
  {
    id: 'A5',
    fn: guard.enforceA5NoInternalArtifacts,
    pass: { values: ['Author-facing instructions only.'] },
    fail: { values: ['Generated by JM1 Automation. artifactId abc.'] },
  },
  { id: 'B1', fn: guard.enforceB1TrimSize, pass: { widthIn: 6, heightIn: 9 }, fail: { widthIn: 8.5, heightIn: 11 } },
  {
    id: 'B2',
    fn: guard.enforceB2FrontMatterSequence,
    pass: { elements: ['half-title', 'title', 'copyright', 'disclaimer', 'dedication', 'toc', 'introduction'] },
    fail: { elements: ['toc', 'title', 'copyright', 'disclaimer'] },
  },
  {
    id: 'B3',
    fn: guard.enforceB3Pagination,
    pass: validPagination,
    fail: { ...validPagination, firstChapterRecto: false },
  },
  { id: 'B4', fn: guard.enforceB4SingleDisclaimer, pass: { disclaimerCount: 1 }, fail: { disclaimerCount: 13, containsLibraryLabels: true } },
  { id: 'B5', fn: guard.enforceB5ConditionalLegalFields, pass: { renderedText: 'Copyright 2026 Jackie Smith Jr.' }, fail: { renderedText: 'LCCN:\nCopyright 2026' } },
  {
    id: 'B6',
    fn: guard.enforceB6IsbnByFormat,
    pass: { contractedFormats: ['print'], renderedIsbns: [{ format: 'print', isbn: '9780000000000' }] },
    fail: { contractedFormats: ['ebook'], renderedIsbns: [{ format: 'print', isbn: '9780000000000' }] },
  },
  { id: 'B7', fn: guard.enforceB7NoSampleContent, pass: { renderedText: 'Chapter One' }, fail: { renderedText: 'Vellum Reviews sample blurb' } },
  {
    id: 'B8',
    fn: guard.enforceB8TocExclusions,
    pass: { tocEntries: ['January 1'], approvedHeadings: ['January 1'] },
    fail: { tocEntries: ['Soul Dive - February 13'], approvedHeadings: ['February 13'] },
  },
  { id: 'C1', fn: guard.enforceC1LoginAvailability, pass: { loginRendered: true, knownGoodAuthPasses: true }, fail: { loginRendered: false, knownGoodAuthPasses: true } },
  { id: 'C2', fn: guard.enforceC2IdentityResolution, pass: { activeAuthor: true, matches: [{ contactId: 'contact-1' }] }, fail: { activeAuthor: true, matches: [{ contactId: 'a' }, { contactId: 'b' }] } },
  { id: 'C3', fn: guard.enforceC3PackageReviewAction, pass: { ctas: [{ label: 'Review Package and Reply', href: 'https://jmerrill.pub/author/portal' }] }, fail: { ctas: [{ label: 'Review Package and Reply' }] } },
  { id: 'D1', fn: guard.enforceD1DuplicateTitlePrevention, pass: { activeMatches: [], authorWorkKey: 'author:title' }, fail: { activeMatches: [{ titleId: 'title-1' }], authorWorkKey: 'author:title' } },
  { id: 'D2', fn: guard.enforceD2AutoAdvanceOnApproval, pass: { approvedAt: '2026-08-04T00:00:00Z', now: '2026-08-04T12:00:00Z' }, fail: { approvedAt: '2026-08-02T00:00:00Z', now: '2026-08-04T12:00:00Z' } },
  { id: 'D3', fn: guard.enforceD3SampleDataExclusion, pass: { assets: [{ name: 'real title', tags: [], authorFacingAdjacent: true }] }, fail: { assets: [{ name: 'demo', tags: ['SAMPLE_ONLY'], authorFacingAdjacent: true }] } },
  { id: 'D4', fn: guard.enforceD4SchedulingTargetAuthority, pass: { availabilityIdentity: 'jm1-admin@jmerrill.one', writeIdentity: 'jm1-admin@jmerrill.one' }, fail: { availabilityIdentity: 'scheduling@jmerrill.one', writeIdentity: 'jm1-admin@jmerrill.one' } },
]

for (const item of cases) {
  test(`${item.id} pass case allows governed action`, () => {
    assert.doesNotThrow(() => item.fn(item.pass))
  })

  test(`${item.id} fail case blocks and exposes execution-log event id`, () => {
    assert.throws(
      () => item.fn(item.fail),
      (error) => {
        assert.equal(error.guardId, item.id)
        assert.equal(error.executionLogEventId, `CANON_GUARD_FAILURE_${item.id}`)
        const failureLog = guard.canonGuardFailureLog({
          guardId: error.guardId,
          failureCode: error.failureCode,
          detail: error.message,
        })
        assert.equal(failureLog.actionType, `CANON_GUARD_FAILURE_${item.id}`)
        assert.match(failureLog.description, new RegExp(`Canon guard ${item.id} blocked execution`))
        return true
      },
    )
  })
}

test('B3 approved print canon: Chapter 1 recto passes', () => {
  assert.doesNotThrow(() => guard.enforceB3Pagination(validPagination))
})

test('B3 approved print canon: Chapter 1 verso fails', () => {
  assert.throws(() => guard.enforceB3Pagination({ ...validPagination, firstChapterRecto: false }), /CHAPTER_ONE_NOT_RECTO/)
})

test('B3 approved print canon: later chapter recto by natural flow passes', () => {
  assert.doesNotThrow(() => guard.enforceB3Pagination({
    ...validPagination,
    laterChapterStarts: [{ chapterLabel: 'Chapter 2', pageSide: 'recto', artificialBlankPageBefore: false }],
  }))
})

test('B3 approved print canon: later chapter verso by natural flow passes', () => {
  assert.doesNotThrow(() => guard.enforceB3Pagination({
    ...validPagination,
    laterChapterStarts: [{ chapterLabel: 'Chapter 2', pageSide: 'verso', artificialBlankPageBefore: false }],
  }))
})

test('B3 approved print canon: artificial blank page before later chapter fails', () => {
  assert.throws(
    () => guard.enforceB3Pagination({
      ...validPagination,
      laterChapterStarts: [{ chapterLabel: 'Chapter 2', pageSide: 'recto', artificialBlankPageBefore: true }],
    }),
    /LATER_CHAPTER_FORCED_RECTO/,
  )
})

test('B3 approved print canon: chapter-opening header visible fails', () => {
  assert.throws(() => guard.enforceB3Pagination({ ...validPagination, chapterOpeningHeaderVisible: true }), /CHAPTER_OPENING_HEADER_VISIBLE/)
})

test('B3 approved print canon: chapter-opening footer visible fails', () => {
  assert.throws(() => guard.enforceB3Pagination({ ...validPagination, chapterOpeningFooterVisible: true }), /CHAPTER_OPENING_FOOTER_VISIBLE/)
})

test('B3 approved print canon: chapter-opening folio visible fails', () => {
  assert.throws(() => guard.enforceB3Pagination({ ...validPagination, chapterOpeningFolioVisible: true }), /CHAPTER_OPENING_FOLIO_VISIBLE/)
})

test('B3 approved print canon: continuation-page running header is required', () => {
  assert.doesNotThrow(() => guard.enforceB3Pagination(validPagination))
  assert.throws(() => guard.enforceB3Pagination({ ...validPagination, continuationPageRunningHeaderPresent: false }), /CONTINUATION_RUNNING_HEADER_MISSING/)
})

test('B3 approved print canon: continuation-page folio is required', () => {
  assert.doesNotThrow(() => guard.enforceB3Pagination(validPagination))
  assert.throws(() => guard.enforceB3Pagination({ ...validPagination, continuationPageFolioPresent: false }), /CONTINUATION_FOLIO_MISSING/)
})

test('prior incorrect later-chapters-recto rule cannot re-enter through Bootstrap', () => {
  assert.match(bootstrap, /subsequentChapters: 'NATURAL_FLOW'/)
  assert.doesNotMatch(bootstrap, /subsequentChapters: 'RECTO'/)
})

test('generated or historical evidence cannot override approved print canon in guard fixtures', () => {
  const unapprovedEvidenceRecord = {
    provenance: 'GENERATED_EVIDENCE',
    printProduction: {
      chapter1: 'RECTO',
      subsequentChapters: 'RECTO',
    },
  }
  const approvedCanon = {
    provenance: 'APPROVED_CANON',
    printProduction: {
      chapter1: 'RECTO',
      subsequentChapters: 'NATURAL_FLOW',
    },
  }

  assert.equal(unapprovedEvidenceRecord.provenance, 'GENERATED_EVIDENCE')
  assert.equal(approvedCanon.printProduction.subsequentChapters, 'NATURAL_FLOW')
  assert.notEqual(unapprovedEvidenceRecord.provenance, 'APPROVED_CANON')
})

test('canon guard module is loaded from the repository source under test', () => {
  assert.match(source, /export function enforceB3Pagination/)
  assert.equal(typeof guard.enforceB3Pagination, 'function')
})
