import assert from 'node:assert/strict'
import test from 'node:test'
import {
  createRequire,
} from 'node:module'

const require = createRequire(import.meta.url)
const policy = require('../azure-functions/diagnostic-ai-runner/src/policy/canonPolicyLayer.js')

test('policy registry exposes every required resolver with canonical decision shape', () => {
  const resolvers = new Set(policy.POLICY_REGISTRY.map((row) => row.resolver))
  for (const resolver of [
    'resolvePaymentAuthority',
    'resolveCommunicationAuthority',
    'resolveIdentityAuthority',
    'resolveArtifactAuthority',
    'resolveEditorialStageAuthority',
    'resolvePublicationIntentAuthority',
    'resolveProductionAuthority',
    'resolveBlock05ProductionAuthority',
    'resolveDistributionAuthority',
    'resolveCadenceAuthority',
    'resolveWaitingOnAuthority',
    'resolveLegacySystemAuthority',
  ]) {
    assert.equal(resolvers.has(resolver), true, `${resolver} missing from registry`)
  }
  const decision = policy.resolvePaymentAuthority({ processor: 'STRIPE' })
  for (const field of [
    'POLICY',
    'POLICY_VERSION',
    'DECISION',
    'AUTHORITY_SOURCE',
    'SOURCE_RECORD',
    'EVIDENCE',
    'REASON',
    'OVERRIDE_ALLOWED',
    'OVERRIDE_REQUIRED',
    'OVERRIDE_AUTHORITY',
    'LEGACY_ALLOWED',
    'MUTATION_ALLOWED',
  ]) {
    assert.equal(Object.hasOwn(decision, field), true, `${field} missing`)
  }
})

test('new Publishing payments allow Stripe and deny MoonClerk fallback', () => {
  assert.equal(policy.resolvePaymentAuthority({ processor: 'STRIPE', context: 'NEW_PUBLISHING_TRANSACTION' }).MUTATION_ALLOWED, true)
  const denied = policy.resolvePaymentAuthority({ processor: 'MoonClerk', context: 'NEW_PUBLISHING_TRANSACTION' })
  assert.equal(denied.DECISION, 'DENY')
  assert.equal(denied.MUTATION_ALLOWED, false)
  assert.equal(denied.violationEvent, 'PAYMENT_PROCESSOR_CANON_VIOLATION')
  const legacy = policy.resolvePaymentAuthority({ processor: 'MoonClerk', context: 'LEGACY_RECONCILIATION' })
  assert.equal(legacy.DECISION, 'LEGACY_RECONCILIATION_ONLY')
  assert.equal(legacy.LEGACY_ALLOWED, true)
})

test('communication authority requires ACS sender, Publishing reply-to, Publishing CC, and HTML', () => {
  const allowed = policy.resolveCommunicationAuthority({
    from: 'publishing@email.jmerrill.one',
    replyTo: 'publishing@jmerrill.one',
    to: ['author@example.com'],
    cc: ['publishing@jmerrill.one'],
    html: '<!doctype html><html><body>Good day.</body></html>',
  })
  assert.equal(allowed.MUTATION_ALLOWED, true)

  for (const input of [
    { from: 'noreply@email.jmerrill.one', replyTo: 'publishing@jmerrill.one', to: ['author@example.com'], cc: ['publishing@jmerrill.one'], html: '<!doctype html><html></html>' },
    { from: 'publishing@email.jmerrill.one', replyTo: 'noreply@email.jmerrill.one', to: ['author@example.com'], cc: ['publishing@jmerrill.one'], html: '<!doctype html><html></html>' },
    { from: 'publishing@email.jmerrill.one', replyTo: 'publishing@jmerrill.one', to: ['author@example.com'], cc: [], html: '<!doctype html><html></html>' },
    { from: 'publishing@email.jmerrill.one', replyTo: 'publishing@jmerrill.one', to: ['author@example.com'], cc: ['publishing@jmerrill.one'], text: 'plain only' },
  ]) {
    assert.equal(policy.resolveCommunicationAuthority(input).DECISION, 'DENY')
  }
})

test('identity authority blocks the Indomitable / Atta fallback regression', () => {
  const denied = policy.resolveIdentityAuthority({
    authorName: 'Atta Darko',
    title: 'Indomitable',
    opportunityId: '455daa4a-629f-f111-b8dc-6045bdd69678',
  })
  assert.equal(denied.DECISION, 'DENY')
  assert.equal(denied.violationEvent, 'AUTHOR_TITLE_IDENTITY_CANON_VIOLATION')
})

test('author-facing artifact safety blocks internal metadata leakage', () => {
  assert.equal(policy.resolveArtifactAuthority({ text: 'Your Developmental Review is ready.' }).MUTATION_ALLOWED, true)
  for (const text of [
    'Generated by JMI Automation',
    'correlationId: abc',
    'checksum: deadbeef',
    'Dataverse workflow record',
    'AUTHOR_REVIEW_RESPONSE',
  ]) {
    assert.equal(policy.resolveArtifactAuthority({ text }).DECISION, 'DENY')
  }
})

test('superseded artifacts cannot become current production authority', () => {
  const denied = policy.resolveArtifactSupersessionAuthority({
    artifactId: 'proof-393',
    status: 'SUPERSEDED',
    supersededBy: 'proof-275',
  })
  assert.equal(denied.DECISION, 'DENY')
  assert.equal(denied.violationEvent, 'SUPERSEDED_ARTIFACT_AUTHORITY_VIOLATION')
})

test('editorial gates require upstream author approval and cadence eligibility', () => {
  assert.equal(policy.resolveEditorialStageAuthority({ stageCode: 'EDITORIAL_REVIEW' }).MUTATION_ALLOWED, true)
  assert.equal(policy.resolveEditorialStageAuthority({ stageCode: 'LINE_EDITING', priorAuthorGateCleared: false }).DECISION, 'DENY')
  assert.equal(policy.resolveEditorialStageAuthority({
    stageCode: 'LINE_EDITING',
    priorAuthorGateCleared: true,
    cadenceEligible: false,
    scheduledReleaseAt: '2026-08-26T02:01:42Z',
  }).DECISION, 'HUMAN_GATE')
})

test('publication intent prevents commissioning titles from requiring release metadata', () => {
  const commissioning = policy.resolvePublicationIntentAuthority({ publicationIntent: 'COMMISSIONING' })
  assert.equal(commissioning.MUTATION_ALLOWED, true)
  assert.equal(commissioning.isbnRequired, false)
  assert.equal(commissioning.distributionRequired, false)
  const commercial = policy.resolvePublicationIntentAuthority({ publicationIntent: 'COMMERCIAL_RELEASE' })
  assert.equal(commercial.isbnRequired, true)
})

test('production authority fails closed when full-wrap inputs are missing', () => {
  const denied = policy.resolveProductionAuthority({
    publicationIntent: 'COMMISSIONING',
    trimSize: '6 x 9',
    pageCount: 275,
    imprint: 'J Merrill Publishing',
    sourceAssets: [{ type: 'FRONT_COVER', location: 'sharepoint://front-cover' }],
  })
  assert.equal(denied.DECISION, 'DENY')
  assert.deepEqual(denied.missing, ['BACK_COVER_COPY'])
})

test('Block 05 production authority blocks entry, stale artifacts, and distribution submission', () => {
  const entry = policy.resolveBlock05ProductionAuthority({
    phase: 'ENTRY',
    productionReady: true,
    finalEditorialManuscriptId: 'artifact-1',
    finalEditorialChecksum: 'a'.repeat(64),
    editorialApprovalsComplete: true,
    styleSheetAvailable: true,
    productionNotesAvailable: true,
    activeTitleProject: true,
    formatEntitlementsResolved: true,
  })
  assert.equal(entry.DECISION, 'DENY')
  assert.equal(entry.missing.includes('FINAL_EDITORIAL_CERTIFIED'), true)

  const final = policy.resolveBlock05ProductionAuthority({
    phase: 'FINAL_CERTIFICATION',
    scopeLockComplete: true,
    requiredWorkstreamsCertified: true,
    requiredAuthorApprovalsComplete: true,
    technicalValidationsPass: true,
    finalArtifactsIdentified: true,
    checksumsVerified: true,
    publicationMetadataReady: true,
    accessibilitySatisfiedOrGoverned: true,
    crossFormatSynchronizationPass: true,
    handoffPackageComplete: true,
    attemptedActions: ['DISTRIBUTION_SUBMISSION'],
  })
  assert.equal(final.DECISION, 'DENY')
  assert.equal(final.missing.includes('BLOCK05_DISTRIBUTION_SUBMISSION_FORBIDDEN'), true)

  const allowed = policy.resolveBlock05ProductionAuthority({
    phase: 'FINAL_CERTIFICATION',
    scopeLockComplete: true,
    requiredWorkstreamsCertified: true,
    requiredAuthorApprovalsComplete: true,
    technicalValidationsPass: true,
    finalArtifactsIdentified: true,
    checksumsVerified: true,
    publicationMetadataReady: true,
    accessibilitySatisfiedOrGoverned: true,
    crossFormatSynchronizationPass: true,
    handoffPackageComplete: true,
  })
  assert.equal(allowed.MUTATION_ALLOWED, true)
  assert.equal(allowed.publicationAssetsReadyAllowed, true)
})

test('waiting-on authority denies author wait without a delivered current request', () => {
  assert.equal(policy.resolveWaitingOnAuthority({
    waitingOn: 'WAITING_ON_AUTHOR',
    currentAuthorRequestDelivered: false,
  }).DECISION, 'DENY')
  assert.equal(policy.resolveWaitingOnAuthority({
    waitingOn: 'WAITING_ON_AUTHOR',
    currentAuthorRequestDelivered: true,
    unconsumedAuthorResponsePresent: false,
  }).MUTATION_ALLOWED, true)
  assert.equal(policy.resolveWaitingOnAuthority({
    waitingOn: 'WAITING_ON_SYSTEM',
  }).DECISION, 'DENY')
})
