import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = process.cwd()
const EXCLUDED_DIRS = new Set(['.git', 'node_modules', '.next', 'out', 'coverage'])
const EXTENSIONS = new Set(['.js', '.mjs', '.ts', '.tsx', '.json', '.md'])

const DRIFT_RULES = [
  ['NEW_NON_STRIPE_PAYMENTS', /\bMoonClerk\b|\bmoonclerk\b/g],
  ['WRONG_PUBLISHING_EMAILS', /\b(?:noreply|NoReply|DoNotReply|donotreply)@|@jmerrill\.pub\b/g],
  ['IDENTITY_MISMATCHES', /Atta Darko[\s\S]{0,120}Indomitable|Indomitable[\s\S]{0,120}Atta Darko/g],
  ['UNSAFE_AUTHOR_ARTIFACTS', /Generated by JMI Automation|Generated by JM1 Automation|correlationId|artifactId|execution log|Dataverse workflow record/g],
  ['SUPERSEDED_CURRENT_ARTIFACTS', /SUPERSEDED[\s\S]{0,120}(current|CURRENT|authority|AUTHORITY)/g],
  ['PUBLICATION_INTENT_VIOLATIONS', /COMMISSIONING[\s\S]{0,120}(ISBN_REQUIRED|barcode required|distribution required|publication launch required)/g],
  ['EDITORIAL_GATE_VIOLATIONS', /(LINE_EDIT|LINE_EDITING|COPYEDIT|COPYEDITING|PROOFREADING)[\s\S]{0,160}(author gate bypass|without author approval|AUTHOR_APPROVAL_REQUIRED\s*=\s*false)/gi],
  ['CADENCE_VIOLATIONS', /(CADENCE_BYPASS|cadence bypass|rush[\s\S]{0,80}without approval)/gi],
  ['WAITING_ON_MISCLASSIFICATIONS', /WAITING_ON_AUTHOR[\s\S]{0,160}(request absent|unconsumed author response|no delivered request)/gi],
  ['LEGACY_NEW_WORK_REFERENCES', /MoonClerk[\s\S]{0,120}(new work|new Publishing|fallback)/g],
]

function walk(dir, files = []) {
  for (const name of readdirSync(dir)) {
    if (EXCLUDED_DIRS.has(name)) continue
    const path = join(dir, name)
    const stat = statSync(path)
    if (stat.isDirectory()) walk(path, files)
    else if (EXTENSIONS.has(path.slice(path.lastIndexOf('.')))) files.push(path)
  }
  return files
}

function classifyMatch(file, line, text) {
  const path = relative(ROOT, file)
  if (/canonPolicyLayer\.js$|jm1-canon-guard\.ts$/.test(path)) return 'HISTORICAL_EVIDENCE_ONLY'
  if (path.includes('docs/operations/generated/')) return 'HISTORICAL_EVIDENCE_ONLY'
  if (path.includes('test/') || path.includes('scripts/') || path.includes('docs/')) return 'HISTORICAL_EVIDENCE_ONLY'
  if (/LEGACY_RECONCILIATION|grandfathered|READ_ONLY_EVIDENCE|PROHIBITED_FOR_NEW_WORK/.test(text)) return 'HISTORICAL_EVIDENCE_ONLY'
  if (/TODO|UNKNOWN|MISSING/.test(text)) return 'TRUE_HUMAN_REVIEW'
  return 'DETERMINISTIC_REPAIR'
}

const files = walk(ROOT)
const findings = Object.fromEntries(DRIFT_RULES.map(([key]) => [key, []]))

for (const file of files) {
  const text = readFileSync(file, 'utf8')
  const lines = text.split(/\r?\n/)
  for (const [key, regex] of DRIFT_RULES) {
    regex.lastIndex = 0
    let match
    while ((match = regex.exec(text))) {
      const line = text.slice(0, match.index).split(/\r?\n/).length
      const excerpt = lines[line - 1]?.trim().slice(0, 240) || ''
      findings[key].push({
        file: relative(ROOT, file),
        line,
        classification: classifyMatch(file, line, excerpt),
        excerpt,
      })
    }
  }
}

const counts = Object.fromEntries(Object.entries(findings).map(([key, rows]) => [key, rows.length]))
const byClassification = Object.fromEntries(Object.entries(findings).map(([key, rows]) => {
  const classified = rows.reduce((acc, row) => {
    acc[row.classification] = (acc[row.classification] || 0) + 1
    return acc
  }, {})
  return [key, classified]
}))

console.log(JSON.stringify({
  audit: 'JM1_RUNTIME_POLICY_DRIFT_AUDIT',
  verifiedAt: new Date().toISOString(),
  counts,
  byClassification,
  findings,
}, null, 2))
