#!/usr/bin/env python3
"""Validate PROGRAM-008 author review package folders."""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

from pypdf import PdfReader


NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
INTERNAL_PATTERNS = re.compile(
    r"JM1 Automation|Generated by:|Generated at:|Source artifact|Source checksum|Correlation:|"
    r"EDITORIAL-RUNTIME|artifact id|checksum|Current Execution State|EXECUTING|QA Evidence|"
    r"Change Ledger|Line-Level Deferral Queue|Continuity / Repetition Candidates|"
    r"Developmentally Edited Manuscript -|Proofread Manuscript -|workflow record|execution log|"
    r"technical diagnostics|production memo|publisher review note",
    re.I,
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def docx_text(path: Path) -> str:
    with zipfile.ZipFile(path) as archive:
        xml = archive.read("word/document.xml")
    root = ET.fromstring(xml)
    return "\n".join("".join(t.text or "" for t in p.findall(".//w:t", NS)) for p in root.findall(".//w:p", NS))


def pdf_text(path: Path) -> str:
    reader = PdfReader(str(path))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def pdf_pages(path: Path) -> int:
    reader = PdfReader(str(path))
    return len(reader.pages)


def shell_pages(path: Path) -> int | None:
    try:
        output = subprocess.check_output(["pdfinfo", str(path)], text=True)
    except Exception:
        return None
    for line in output.splitlines():
        if line.startswith("Pages:"):
            return int(line.split(":", 1)[1].strip())
    return None


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: program008_package_qa.py OUTPUT_ROOT", file=sys.stderr)
        return 2
    root = Path(sys.argv[1])
    ecr = {record["slug"]: record for record in json.loads((root / "evidence" / "ecr-preview-results.json").read_text())}
    records = []
    failures = []
    for package_dir in sorted((root / "packages").iterdir()):
        if not package_dir.is_dir():
            continue
        slug = package_dir.name
        files = sorted(path for path in package_dir.iterdir() if path.is_file())
        docx = [path for path in files if path.name.endswith("-Author-Review-Manuscript.docx")]
        notes = [path for path in files if path.name.endswith("-Author-Review-Notes.pdf")]
        instructions = [path for path in files if path.name.endswith("-Review-Instructions.pdf")]
        checksums = {path.name: sha256(path) for path in files}
        internal_count = 0
        for path in files:
            if path.suffix.lower() == ".docx":
                text = docx_text(path)
            elif path.suffix.lower() == ".pdf":
                text = pdf_text(path)
            else:
                text = path.read_text(errors="ignore")
            internal_count += len(INTERNAL_PATTERNS.findall(text))
        pdf_open = all(pdf_pages(path) == shell_pages(path) == 1 for path in notes + instructions)
        ecr_record = ecr.get(slug, {})
        record = {
            "slug": slug,
            "attachments": [path.name for path in files],
            "attachmentCount": len(files),
            "attachmentsDistinct": len(set(checksums.values())) == len(files),
            "authorReviewManuscript": "PASS" if len(docx) == 1 else "FAIL",
            "authorReviewNotes": "PASS" if len(notes) == 1 else "FAIL",
            "reviewInstructions": "PASS" if len(instructions) == 1 else "FAIL",
            "open": "PASS" if len(docx) == 1 and zipfile.is_zipfile(docx[0]) and pdf_open else "FAIL",
            "internalArtifacts": internal_count,
            "ecr": ecr_record.get("status", "FAIL"),
            "html": "PASS" if Path(ecr_record.get("html", "")).exists() else "FAIL",
            "plainText": "PASS" if Path(ecr_record.get("text", "")).exists() else "FAIL",
            "portal": "OPTIONAL",
            "sender": ecr_record.get("sender"),
            "replyTo": ecr_record.get("replyTo"),
            "checksums": checksums,
        }
        if (
            record["attachmentCount"] != 3
            or not record["attachmentsDistinct"]
            or record["open"] != "PASS"
            or record["internalArtifacts"] != 0
            or record["ecr"] != "PASS"
            or record["html"] != "PASS"
            or record["plainText"] != "PASS"
            or record["sender"] != "publishing@email.jmerrill.one"
            or record["replyTo"] != "publishing@jmerrill.one"
        ):
            failures.append(slug)
        records.append(record)
    result = {"status": "PASS" if not failures else "FAIL", "failures": failures, "titles": records}
    print(json.dumps(result, indent=2))
    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())
